### ISSUE TITLE
Add relevant info for the home, about and contact page.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#10]
# About issue-
Add relevant info to the `app.js` file for the home, about and the contact page.

- for contact page add email `aaradhyasharma218@gmail.com` for any queries.

**Comment by luckykumarirai** [comment]
I would like to contribute to this. Please assign me this issue.

**Comment by Niveditha18** [comment]
I'm willing to contribute to this issue. - Niveditha from JWoc

**Comment by Niveditha18** [comment]
Hey Pranav, can you please tell me on which topic specifically should I write content about?
