### ISSUE TITLE
Design a Favicon for the website

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#105]
### Feature request
Design a Favicon and add HTML tag for it to the website.

### Describe the solution you'd like
Favicon can be designed using different tools such as illustrator ,canva etc.
Color combinations should be good and should match the aesthetics of the website.

### Describe how this feature will be useful to our readers.
Helps identify the website when multiple tabs are open.

**Comment by HarshitAditya27** [comment]
Hi, I would like to work on this issue, I am planning to make a favicon which similar to the symbol used in your readme file. Will that be okay?  
If not then can you suggest to me some other methods or options to do it as this is my first open-source project.

**Comment by Pranav016** [comment]
> Hi, I would like to work on this issue, I am planning to make a favicon which similar to the symbol used in your readme file. Will that be okay?
> If not then can you suggest to me some other methods or options to do it as this is my first open-source project.

Yes, you can use the website logo that you can find in the `assets` folder or you can design something on your own.
If this is your first time contributing do read the CONTRIBUTING.md and follow best practices.

Are you contributing under JWoC or any open-source program? Do mention, then I'll add necessary labels.
Happy Learning!

**Comment by HarshitAditya27** [comment]
Sir, I have a doubt, I have created the favicon but I am unable to run the website using the terminal and mongod server 
I have followed these steps :- 
1,git clone https://github.com/ <your user-name> /BlogSite.git 
2, cd Blogsite. 
3, Exected npm install in the terminal. 
4, Started the mongod server. 
5, Executed node app in the terminal. 
6, After the execution, the terminal was showing server started on port 3000 and after that many warnings displayed. 
I am sending you the screenshots of the error and all the steps I did, can you please help me where I am going wrong and I am contributing under MWoC (Mexili Org).
![Screenshot (569)](https://user-images.githubusercontent.com/71604531/106637931-4f585700-65a9-11eb-92b7-08acb64b5b1c.png)
![Screenshot (570)](https://user-images.githubusercontent.com/71604531/106637935-51221a80-65a9-11eb-8f23-feb02e709ff6.png)
![error](https://user-images.githubusercontent.com/71604531/106638018-66974480-65a9-11eb-8143-a1d7b1e34c7e.png)

**Comment by Pranav016** [comment]
> Sir, I have a doubt, I have created the favicon but I am unable to run the website using the terminal and mongod server
> I have followed these steps :-
> 1,git clone https://github.com/ /BlogSite.git
> 2, cd Blogsite.
> 3, Exected npm install in the terminal.
> 4, Started the mongod server.
> 5, Executed node app in the terminal.
> 6, After the execution, the terminal was showing server started on port 3000 and after that many warnings displayed.
> I am sending you the screenshots of the error and all the steps I did, can you please help me where I am going wrong and I am contributing under MWoC (Mexili Org).

Refer to this point in the README-

![image](https://user-images.githubusercontent.com/54665036/106638948-6c415a00-65aa-11eb-8c54-47dcd2d72362.png)

Change the url to the one mentioned here

**Comment by HarshitAditya27** [comment]
Sir, after executing you following steps the terminal is showing syntax error.
![Screenshot (571)](https://user-images.githubusercontent.com/71604531/106640747-6ba9c300-65ac-11eb-89f8-c31e2a6d7d67.png)

**Comment by Pranav016** [comment]
> > Sir, after executing your following steps the terminal is showing  SyntaxError: Unexpected token ':'

Try again `const URL = 'mongodb://localhost:27017/blogDB';`
Just make the url a string.

**Comment by HarshitAditya27** [comment]
Thanks a lot, sir it's working!!!, one last question I wanted to ask can I keep my branch name as favicon?

**Comment by Pranav016** [comment]
> Thanks a lot, sir it's working!!!, one last question I wanted to ask can I keep my branch name as favicon?

Sure :+1:

**Comment by HarshitAditya27** [comment]
Sir, I have created the pull request I hope you can see that :)
