### ISSUE TITLE
Add a new background for the website pages.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#109]
### Feature request-
Add new background for the website pages.

### Describe the solution you'd like
Design a background or suggest somethings to add to the website background. Make sure that the background is light and does not overpower the current aesthetics and the other components stay visible.

### Describe how this feature will be useful to our readers.
Improves user experience.

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue as a mentee of Jwoc21.
* Adding appropriate backgrounds for each page.
* Make it related to its content.

**Comment by Pranav016** [comment]
@karunkarthik-git are you still working on this?

**Comment by archana-9430** [comment]
Please allow me to work on this.

**Comment by Pranav016** [comment]
> Please allow me to work on this.

Which program are you working under? I'll add the appropriate labels.

**Comment by archana-9430** [comment]
> > Please allow me to work on this.
> 
> Which program are you working under? I'll add the appropriate labels.

GSSoC

**Comment by Pranav016** [comment]
> > > Please allow me to work on this.
> > 
> > 
> > Which program are you working under? I'll add the appropriate labels.
> 
> GSSoC

Points might not be added for GSSoC since it's development phase hasn't started yet..

Issues worked upon in the development period will only be counted. Let me know if you'd still like to work.

**Comment by archana-9430** [comment]
> > > > Please allow me to work on this.
> > > 
> > > 
> > > Which program are you working under? I'll add the appropriate labels.
> > 
> > 
> > GSSoC
> 
> Points might not be added for GSSoC since it's development phase hasn't started yet..
> 
> Issues worked upon in the development period will only be counted. Let me know if you'd still like to work on this.

I would like to work on this, when the development phase will start . However, I have initiated my work on this.

**Comment by archana-9430** [comment]
Please allow me to work during the development phase of GSSoC.

**Comment by Pranav016** [comment]
> > > > > Please allow me to work on this.
> > > > 
> > > > 
> > > > Which program are you working under? I'll add the appropriate labels.
> > > 
> > > 
> > > GSSoC
> > 
> > 
> > Points might not be added for GSSoC since it's development phase hasn't started yet..
> > Issues worked upon in the development period will only be counted. Let me know if you'd still like to work on this.
> 
> I would like to work on this, when the development phase will start . However, I have initiated my work on this.

Development phase starts after 10-15 days, I can't assign this to you for that long. Don't worry, new issues are being created all the time and you can always take any issue like in the future. Meanwhile you can get familiar with the codebase.

If you still want to work on this without any points, let me know.

**Comment by Aayush-hub** [comment]
@Pranav016  Can I work on issue for  #GSsoc21?

**Comment by Aayush-hub** [comment]
@Pranav016  Can I work on this? #MWOC

**Comment by Aayush-hub** [comment]
@Pranav016 Can you please provide some reference background image that you want so that I can get a better picture?

**Comment by Pranav016** [comment]
> @Pranav016 Can you please provide some reference background image that you want so that I can get a better picture?

I don't have any reference image. But I have this in mind that rather than using any image, use any good illustration or even a plain linear gradient with good color combination would look good.
Also change the background of the navbar in contrast with the background. 

Also the background stays somewhat consistent in mobile view as well.
