### ISSUE TITLE
Design a new logo for the Project.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#11]
# About issue-
- Design a new logo for the project and make sure to include 2-3 options to choose from while making a pull request.

- Designing a logo would also mean updating the current README banner after the final logo is chosen.

**Comment by luckykumarirai** [comment]
I would like to contribute to this issue.

**Comment by Pranav016** [comment]
> I would like to contribute to this issue.

Sure, issues will start getting assigned from 21st Jan onwards. Till then get familiar with the project base and continue to experiment with it🙂

**Comment by Niveditha18** [comment]
Hello @Pranav016, I'm willing to work on this issue

**Comment by anubhab1710** [comment]
Hello, @Pranav016 I would like to contribute to this project by taking up and resolve this issue. I have a fair understanding of the project's aim and being a graphic designer myself (**I have created JWOC's official logo too**), I will be able to create a new logo as well as make a new banner for the Readme file. _I request you to kindly assign this issue to me_

**Comment by Pranav016** [comment]
Since Lucky and Niveditha have already gotten an issue assigned so as per JWoC rules at a time I can only assign not more than 1 issue to the same person. So assigning this to you @anubhab1710
