### ISSUE TITLE
Improve the navigation bar.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#110]
### Feature request
Improve the navigation bar and add some animation on hover. 

### Describe the solution you'd like
Add a gradual underline style on hover or add some animation/ style on your own, something that you feel will look good.

### Describe how this feature will be useful to our readers.
Improves user experience.

**Comment by mcmonojit** [comment]
@Pranav016 , I would like to work on this issue.

**Comment by Pranav016** [comment]
> @Pranav016 , I would like to work on this issue.

You can complete previous issue and can get assigned for this one. 👍

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue. Kindly assign it to me @Pranav016 
I'll make the nav bar responsive and give good animations on hover.
