### ISSUE TITLE
Improve footer.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#111]
### Feature request
Add 3 or 4 column footer, use bootstrap or CSS grids. Add some hypothetical information like contact or office. Add social links in one column (use font awesome icons). Suggest some 

### Describe how this feature will be useful to our readers.
Improves user experience

**Comment by luckykumarirai** [comment]
Hello @Pranav016 I would like to contribute as a participant of Jwoc.

**Comment by luckykumarirai** [comment]
@Pranav016 This PR already merged but not reflected in Leaderboard  of JWOC. Please inform them about this.

**Comment by Pranav016** [comment]
> @Pranav016 This PR already merged but not reflected in Leaderboard of JWOC. Please inform them about this.

Ok, I'll look into it

**Comment by Pranav016** [comment]
@luckykumarirai Points for this PR were submitted, might not have been updated by organizing team. I'll remind them 👍
