### ISSUE TITLE
Improve buttons

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#112]
### Feature request
Improve the buttons and add some animations to the buttons on all the website pages. For example, currently the buttons on home page have different animation from buttons on compose or other page.  Improve them and maintain some consistency.

### Describe how this feature will be useful to our readers.
Improves user experience.

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue.

* Making buttons of uniform styling.
* Making button's animation specific to the context.

* Different animations for buttons which perform operations like : 
1.  Delete
2. Compose
3. Search

Assign it to me @Pranav016
