### ISSUE TITLE
Improve text font for the all the text on the website.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#113]
### Feature request
Improve text font for the all the text on the website. You choose a good font from google fonts.

### Describe how this feature will be useful to our readers.
improves user experience

**Comment by mcmonojit** [comment]
@Pranav016 , I am interested to work on this issue. Can I work on this ?

**Comment by Pranav016** [comment]
> @Pranav016 , I am interested to work on this issue. Can I work on this ?

You want to work on this under JWoC or Mexili WoC ? I'll add appropriate labels accordingly

**Comment by mcmonojit** [comment]
> > @Pranav016 , I am interested to work on this issue. Can I work on this ?
> 
> You want to work on this under JWoC or Mexili WoC ? I'll add appropriate labels accordingly

I am working under JWoC.
