### ISSUE TITLE
Align dark mode button to bottom left corner 

### ISSUE THREAD

**Issue by Abhijay007** [ALPHAVIO/BlogSite#114]
### Is your feature request related to a problem? Please describe.
Align dark mode button to bottom left corner  because it looks confusing as the access bot button is already there 

### Describe the solution you'd like
 Just change position to the left in the CSS section of the script file of dark mode js

### Describe alternatives you've considered
you can also place it at the top right corner next to "contact us: 

### Describe how this feature will be useful to our readers.
It improves UI and user experience 

### Additional context

***screenshot***

![dark-mode](https://user-images.githubusercontent.com/64387054/106726608-963d5f80-6630-11eb-871a-30a7683ff436.PNG)

**Comment by Pranav016** [comment]
Sounds good, you want to work on this issue under JWoC or Mexili ? Accordingly I'll add appropriate labels.

**Comment by Abhijay007** [comment]
> Sounds good, you want to work on this issue under JWoC or Mexili ? Accordingly I'll add appropriate labels.

Mexilli

**Comment by Abhijay007** [comment]
sir, I am getting this error while starting the project on the browser (http://localhost:3000/) 

```
(node:10824) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (C:\Users\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\connection.js:693:11)
    at C:\\notmyusername\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\index.js:345:10
    at C:\\notmyusername\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (C:\notmyusername\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\index.js:1135:10)
    at Mongoose.connect (C:\\notmyusername\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\index.js:344:20)
    at Object.<anonymous> (C:\\notmyusername\user\Desktop\Blog Site\BlogSite\app.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
do I need to install anything else other than the setup mentioned in the project readme?

**Comment by Pranav016** [comment]
> sir, I am getting this error while starting the project on the browser (http://localhost:3000/)
> 
> ```
> (node:10824) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
>     at NativeConnection.Connection.openUri (C:\Users\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\connection.js:693:11)
>     at C:\\notmyusername\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\index.js:345:10
>     at C:\\notmyusername\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
>     at new Promise (<anonymous>)
>     at promiseOrCallback (C:\Users\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
>     at Mongoose._promiseOrCallback (C:\notmyusername\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\index.js:1135:10)
>     at Mongoose.connect (C:\\notmyusername\user\Desktop\Blog Site\BlogSite\node_modules\mongoose\lib\index.js:344:20)
>     at Object.<anonymous> (C:\\notmyusername\user\Desktop\Blog Site\BlogSite\app.js:50:10)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:10824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:10824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> do I need to install anything else other than the setup mentioned in the project readme?

Read the setup in the README carefully, you have not changed the url in app.js.

**Comment by Abhijay007** [comment]
> Read the setup in the README carefully, you have not changed the url in app.js.

sir, do I need to change this part:
of app.js

```
//Connecting to Mongo Database using ODM Mongoose-
const URL = process.env.URL;
mongoose.connect(URL, {useNewUrlParser: true, useUnifiedTopology: true});
```

**Comment by Pranav016** [comment]
> ```
> const URL = process.env.URL;
> ```

Only this

**Comment by Abhijay007** [comment]
> > ```
> > const URL = process.env.URL;
> > ```
> 
> Only this

ok, thanks Sir !!

**Comment by Pranav016** [comment]
@Abhijay007 Are you working on this?

**Comment by Abhijay007** [comment]
> @Abhijay007 Are you still working on this?

Yes, @Pranav016 sir if you want I will make a new PR with a single commit, now I figured out where I made the mistake.
