### ISSUE TITLE
Add pull request templates.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#12]
# About issue-
Refer to the [docs](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) and add pull request templates to the Project.

[Reference template](https://github.com/Pranav016/Anyxz/blob/master/.github/pull_request_template.md)

**Comment by pankajkumarbij** [comment]
I would like to contribute as a participant of JWOC.

**Comment by Pranav016** [comment]
> I would like to contribute as a participant of JWOC.

Sure, issues will start getting assigned from 21st Jan onwards. Till then get familiar with the project base and continue to experiment with it🙂

**Comment by karunkarthik-git** [comment]
I'd like to contribute to this as a mentee of Jwoc. Please assign it to me.

**Comment by tusharjain0022** [comment]
I would like to contribute to this issue as a mentee under JWOC.

**Comment by Pranav016** [comment]
Can you work on this ASAP @pankajkumarbij ? I need a proper template to make it easy for me to review PRs and other people are also waiting to take up the issue..

**Comment by pankajkumarbij** [comment]
I will send a PR today.

**Comment by Pranav016** [comment]
Solved via #49
