### ISSUE TITLE
Add Github actions for first time contributors

### ISSUE THREAD

**Issue by Abhijay007** [ALPHAVIO/BlogSite#123]
### Is your feature request related to a problem? Please describe.
Add Github actions for the enhancement of the project

### Describe the solution you'd like

We can add an Interaction bot for first-time contributors to this project to greet them with a message when they raise any issue or make any pull request solving any issue. This makes the project more attractive for contributors.

**Comment by Pranav016** [comment]
Display a message greeting them and telling them to read code of conduct and contribution guidelines (add hyperlinks to them in the message).
