### ISSUE TITLE
Add issue templates for the project.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#13]
# About issue-
Add issue templates for the project. You can refer to the [docs](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) if you need help, how to create issue templates.

**Comment by sahilsaha7773** [comment]
I would like to work on this

**Comment by Pranav016** [comment]
Please don't spam on all issues otherwise I'll have to ban you. You can only work/ get assigned for 2 issues at a time.
Refer to #21

**Comment by sahilsaha7773** [comment]
> Please don't spam on all issues otherwise I'll have to ban you. You can only work/ get assigned for 2 issues at a time.
> Refer to #21

I didn't really mean to spam, I am genuinely interested, anyways...

**Comment by Pranav016** [comment]
> > Please don't spam on all issues otherwise I'll have to ban you. You can only work/ get assigned for 2 issues at a time.
> > Refer to #21
> 
> I didn't really mean to spam, I am genuinely interested, anyways...

Sure, you can work but work on 2 issues at a time 😄 
Also, I'll start assigning issues as soon as JWoC's community bonding period is over. Till then, thank you for your patience.

**Comment by sahilsaha7773** [comment]
> > > Please don't spam on all issues otherwise I'll have to ban you. You can only work/ get assigned for 2 issues at a time.
> > > Refer to #21
> > 
> > 
> > I didn't really mean to spam, I am genuinely interested, anyways...
> 
> Sure, you can work but work on 2 issues at a time 😄
> Also, I'll start assigning issues as soon as JWoC's community bonding period is over. Till then, thank you for your patience.

Got it, thanks!

**Comment by uttu2** [comment]
I would like to contribute in it.

**Comment by tusharjain0022** [comment]
I would like to contribute to this issue as a mentee under JWOC.

**Comment by tusharjain0022** [comment]
@Pranav016 I think you can assign it to me as issues with `easy` label shouldn't take this much of time to complete under the JWOC. I want to contribute to this issue.

**Comment by Pranav016** [comment]
Closed via #45
