### ISSUE TITLE
GitHub action to merge PR from all-contributors bot

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#139]
### Feature request
Set GitHub action to automatically merge pull-requests from all-contributors bot

**Comment by pankajkumarbij** [comment]
I would like to work on this issue.

**Comment by m-code12** [comment]
@Pranav016 I would like to take this up.

**Comment by m-code12** [comment]
I would like to take this up @Pranav016

**Comment by Pranav016** [comment]
> I would like to take this up @Pranav016

I was going to work on this but if you want to work on this go ahead. What labels should I add ?

**Comment by m-code12** [comment]
MWOC

**Comment by m-code12** [comment]
I am thinking of making use of this GitHub action: https://github.com/marketplace/actions/auto-merge-dependency-updates , is this okay?
But I think it won't merge the all-contributors pr's. Do you know any good action which would do this?

**Comment by m-code12** [comment]
@Pranav016 I have pinged you on discord regarding this.

**Comment by Pranav016** [comment]
> @Pranav016 I have pinged you on discord regarding this.

Replied 👍

**Comment by m-code12** [comment]
I tested it in my repo, doesn't seem like it's working.
Here is the test repo : https://github.com/m-code12/Test_repo
It will only merge the dependabot pr's.

**Comment by Pranav016** [comment]
> I tested it in my repo, doesn't seem like it's working.
> Here is the test repo : https://github.com/m-code12/Test_repo
> It will only merge the dependabot pr's.

Try change allowed actors for these two options-
`allcontributors[bot]` and `all-contributors-preview[bot]`.
I was looking for official name for the bot to put in the allowed actors and I think this might work.

**Comment by m-code12** [comment]
> > I tested it in my repo, doesn't seem like it's working.
> > Here is the test repo : https://github.com/m-code12/Test_repo
> > It will only merge the dependabot pr's.
> 
> Try changing allowed actors and play around with these two options-
> `allcontributors[bot]` and `all-contributors-preview[bot]`.
> I was looking for official name for the bot to put in the allowed actors and I think this might work.

I tried but it isn't working out, it is mentioned in the GitHub action that it will automatically approve and merge a PR that only contains dependency updates, based on some rules.

**Comment by Pranav016** [comment]
@m-code12 you can make a PR to add action to merge dependabot PRs, I'll work on merging all-contributors bot PRs.
(points will be given accordingly)
