### ISSUE TITLE
Design a new logo for the ALPHAVIO organization.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#15]

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue, I'm familiar with logo and poster designing. Could you tell more about the organization so I can start once the coding period starts.

**Comment by Pranav016** [comment]
> I'd like to work on this issue, I'm familiar with logo and poster designing. Could you tell more about the organization so I can start once the coding period starts.

We are an open-source organization all about next-gen software and collaboration.

**Comment by anubhab1710** [comment]
Hello @Pranav016 If this issue hasn't been resolved yet by the previous assignee, can I proceed to work on this (since only 1 day is allowed for 'easy' tagged issues)? - Under JWOC

**Comment by Pranav016** [comment]
I am assigning both and both of you can work on this issue and will get points if merged. Karun has also been working on this and updated me. @anubhab1710 is also good at designing so i am also giving him a chance.
