### ISSUE TITLE
Make Unit tests for Node JS application | Feature request

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#152]

**Comment by Itsaadarsh** [comment]
Hey there @Pranav016, I'd like to work on this feature. So if it's not already assigned to anyone I'd like you it assign it to me so that I could get started right away.

**Comment by Pranav016** [comment]
> Hey there @Pranav016, I'd like to work on this feature. So if it's not already assigned to anyone I'd like you it assign it to me so that I could get started right away.

So there is no description added for the issue so let me just tell you what to do, you need to make unit test for the app so that a GitHub action can be used to review each pull request. The tests will run on the PR before reviewing..
Let me know if you want to work on this..

**Comment by Itsaadarsh** [comment]
> > Hey there @Pranav016, I'd like to work on this feature. So if it's not already assigned to anyone I'd like you it assign it to me so that I could get started right away.
> 
> So there is no description added for the issue so let me just tell you what to do, you need to make unit test for the app so that a GitHub action can be used to review each pull request. The tests will run on the PR before reviewing..
> Let me know if you want to work on this..

Yes, I totally get it I'll start writing all the required test cases using `jest` then make a unit testing pipeline using `GitHub Actions` which will run all the test cases once a PR is made, sounds good?

**Comment by ApekshaAgarwal** [comment]
Hey @Pranav016 , I would also like to contribute on this for making unit tests.

**Comment by AnanyaNegi** [comment]
@Itsaadarsh are you still working on this issue?

**Comment by Itsaadarsh** [comment]
Hey @AnanyaNegi, yes I've been working on this you can expect a PR by tomorrow.
