### ISSUE TITLE
Blogsite deployed on heroku is inactive.

### ISSUE THREAD

**Issue by RutvikJ77** [ALPHAVIO/BlogSite#156]
### **Describe the bug**
The links provided in description and readme file for checking the heroku deployment are inactive.

### **To Reproduce**
1. Go to 'https://blogsite321.herokuapp.com/'
2. See error

### **Expected behavior**
The website should be displayed

### **Screenshots**
NA

### **Additional context**
NA

**Comment by Pranav016** [comment]
Yes, I noticed. Thank you for raising the concern. Last night there was issue with the GitHub service but that was fixed today. I am trying to to check the build logs to figure out the issue with its deployment. It'll hopefully be fixed soon.

**Comment by Pranav016** [comment]
@RutvikJ77 Can you confirm if the website is back online ? I have made some changes, there was a production bug.

**Comment by RutvikJ77** [comment]
> @RutvikJ77 Can you confirm if the website is back online ? I have made some changes, there was a production bug.

Yup! Up and running. I am participating in MWoC (Mexilli's Winter of Code).
