### ISSUE TITLE
Improve UI/UX of the Homepage

### ISSUE THREAD

**Issue by RutvikJ77** [ALPHAVIO/BlogSite#159]
### **Describe the bug**
The current homepage to add/compose notes is too cluttered.

### **To Reproduce**
1. Go to 'https://blogsite321.herokuapp.com/'
4. On Hompepage.

### **Expected behavior**
Improving the Gestalt's law of UI which is the correct level of spacing and orientation of buttons would give a different appearance to the website.

### **Screenshots**
![Screenshot 2021-02-12 at 7 15 45 PM](https://user-images.githubusercontent.com/45565999/107776035-15d0da00-6d67-11eb-876c-a1340de08689.png)

### **Additional context**
I would like to take this issue.

**Comment by Pranav016** [comment]
@RutvikJ77 Are you working on this?

**Comment by RutvikJ77** [comment]
Yes, I am. I was finding my way around a few things. One more thing the Org logo folder has repeated images so I guess maybe you should delete it?

**Comment by Pranav016** [comment]
> Yes, I am. I was finding my way around a few things. One more thing the Org logo folder has repeated images so I guess maybe you should delete it?

Ok, keep working 👍
Yeah, I'll take care of the folder.

**Comment by Pranav016** [comment]
Responsive PR got merged, you can work on this now. Please complete it asap otherwise I'll have to change assignment.

**Comment by thaditi** [comment]
Hey! Is this issue still open? I would like to work on this as part of GSSOC'21.

**Comment by Pranav016** [comment]
> Hey! Is this issue still open? I would like to work on this as part of GSSOC'21.

Yes, I can assign it to you. But you can't work under GSSoC, it's dev phase hasn't started yet..
Let me know if you want to work independently

**Comment by RutvikJ77** [comment]
Hey sorry for the delay! I am working on another project right now. @thaditi you can take this issue.

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by Ankita297** [comment]
Can you please elaborate the issue ?

**Comment by Pranav016** [comment]
> Can you please elaborate the issue ?

Actually this issue was raised by @RutvikJ77 so I think he would better be able to explain his vision for this issue.

According to me, it's about correct spacing, margins, orientations and improving the text styles to improve the website visually and improve user experience.

**Comment by RutvikJ77** [comment]
Yes, you are correct @Pranav016. The issue is that there are various unnecessary spaces that somehow disrupt the flow of vision which is crucial in UI terms. 
- Another thing was that the "Anything new?" title should have the compose button in a single line rather than a new one, @Ankita297 you can do it using the span element. The next thing is the buttons there are kind of rigid meaning stiff in their look which you can round them slightly. 
- Additionally, I feel that the search bar is too long to accommodate any new searches. In short, improving the look and feel of the website.

 I know I am critiquing too much but I hope I gave relevant examples to help you understand @Ankita297.

**Comment by Ankita297** [comment]
Thank you @RutvikJ77  for elaborating the issue .
I would like to work on this .

**Comment by Pranav016** [comment]
> Is it will be counted in my GSSoc score ?

Yes, you can make PR anytime. If it gets merged after 8th March then yes it counts towards GSSoC.

**Comment by Ankita297** [comment]
![Daily Journal - Google Chrome 08-03-2021 19_42_35 (2)](https://user-images.githubusercontent.com/67833077/110332720-b654aa00-8046-11eb-8012-733919bb9746.png)

**Comment by Ankita297** [comment]
Sir is it okay ?
Or need some changes .

**Comment by Pranav016** [comment]
> Sir is it okay ?
> Or need some changes .

Make the PR, then I'll review it..

**Comment by anushree71199** [comment]
I would like to contribute to this issue under GSSoc '21 is it open?

**Comment by Aanchal116** [comment]
I would like to work on the issue, is it still open for GSSOC?

**Comment by AnanyaNegi** [comment]
Thank you for your enthusiasm @anushree71199, @mohdjameel2412, @Aanchal116 but this issue has been currently assigned to @Ankita297.
