### ISSUE TITLE
Add MIT LICENSE file to the repository.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#16]
# About issue-
Add MIT LICENSE file to the repository and add its link to the repo README.
Refer to the [documentation](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) for help.

`Copyright to Pranav Mendiratta and ALPHAVIO`

**Comment by tanvimoharir** [comment]
@Pranav016  Hi, I came across this and would like to take this up, I'm new to Open Source so any help/guidance is more than welcome. Please assign this to me and also let me know of any relevant information. Thanks

**Comment by tanvimoharir** [comment]
Created in PR #20

**Comment by Swapna804** [comment]
I would like to work on it

**Comment by tusharjain0022** [comment]
I would like to work on this as a mentee under JWOC.
