### ISSUE TITLE
Add delete button for comments and functionality such that only authenticated user can comment.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#160]
### Is your feature request related to a problem? Please describe.
Add delete button for comments so that any vulgar comments can be deleted and functionality such that only authenticated user can comment. Remove name input-box for comments. 
![image](https://user-images.githubusercontent.com/54665036/107856802-b8b15300-6e50-11eb-8f0a-10946dabc160.png)

### Describe the solution you'd like
* Add functionality such that only authenticated user can comment
* Add delete button for comments so that any vulgar comments can be deleted. For now delete button will be visible to all, not only to the person who has made that comment.
* Since only an authenticated user can comment on posts and instead of taking input for name, use his/ her name from the database for the comment.

### Describe how this feature will be useful to our readers.
Improves user experience

**Comment by aniketlodh** [comment]
Hello,
I would like to work on this issue. The way I would approach the issue is by making a schema for comments and associate it with user schema. Finally adding a delete button to delete it. But I'm comfortable working with passport for authentication. Can I replace JWT with passport and work on this issue?

**Comment by Pranav016** [comment]
> Hello,
> I would like to work on this issue. The way I would approach the issue is by making a schema for comments and associate it with user schema. Finally adding a delete button to delete it. But I'm comfortable working with passport for authentication. Can I replace JWT with passport and work on this issue?

Right now I think we shouldn't shift the whole authentication to passport. I'll have to make a separate issue for this since it would require some large code re-factoring. Let me know if you can work on this issue using the documentation for JWT.

**Comment by aniketlodh** [comment]
Yes, I can work on the issue using the documentation for JWT.

**Comment by Pranav016** [comment]
> Yes, I can work on the issue using the documentation for JWT.

Ok, let me know under which program do you want to work, I'll add the appropriate labels.

**Comment by aniketlodh** [comment]
I would like to work as a separate individual. Actually, I got to know about this project from Girlscript Summer of code's projects page. But till now I haven't got the confirmation whether I'm selected for the program. So I would like to work as an individual until I get any confirmation. Once I get the confirmation, I will let you know.

**Comment by aniketlodh** [comment]
GSSOC

**Comment by Pranav016** [comment]
GSSoC's development phase starts after 10-15 days so points for this issue won't be added but you can work on this independently if you want to.

**Comment by aniketlodh** [comment]
Okay, not a problem. I'll work independently on this issue.
