### ISSUE TITLE
Add constraints for email, username and password during sign-up

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#163]
### Feature request
Add constraints for email, username and password during sign-up

### Describe how this feature will be useful to our readers.
Improves security and helps maintain consistency.

**Comment by ranjal007** [comment]
@Pranav016  Can I work on this issue?

**Comment by Pranav016** [comment]
> @Pranav016 Can I work on this issue?

Yes sure, let me know under which program will be working?

**Comment by ranjal007** [comment]
@Pranav016  Gssoc

**Comment by ranjal007** [comment]
@Pranav016  Can you please elaborate the documentation of setting up the environment. I am not getting which url you are asking to change in app.js

**Comment by Abhijay007** [comment]
@ranjal007 change this part in app.js:

`const URL = process.env.URL;`

to this:

`const URL = 'mongodb://localhost:27017/blogDB';

**Comment by Pranav016** [comment]
> @Pranav016 Gssoc

I don't thing development phase for GSSoC starts till 1st March. You can work on the issue if you want, but you might not get any points for that.

**Comment by Pranav016** [comment]
> @ranjal007 change this part in app.js:
> 
> `const URL = process.env.URL;`
> 
> to this:
> 
> `const URL = 'mongodb://localhost:27017/blogDB';`

Thanks for the assistance @Abhijay007 👍

**Comment by Pranav016** [comment]
@ranjal007 are you still working on this?

**Comment by mcmonojit** [comment]
@Pranav016 , if this issue is open then I would like to work on it.

**Comment by Pranav016** [comment]
> @Pranav016 , if this issue is open then I would like to work on it.

JWoC is over, let me know if you still want to work independently..

**Comment by sukhpreet-singh1** [comment]
@Pranav016 if this issue is open ,can you please assign me this issue?

**Comment by Pranav016** [comment]
> @Pranav016 if this issue is open ,can you please assign me this issue?

Under which program do you want to work? :)

**Comment by sukhpreet-singh1** [comment]
@Pranav016  i am a participant in Girlscript summer of code (GSSOC)

**Comment by Pranav016** [comment]
> @Pranav016 i am a participant in Girlscript summer of code (GSSOC)

GSSoC hasn't started yet.. Do you still want to work?

**Comment by luckykumarirai** [comment]
@Pranav016 I would like to contribute.

**Comment by chehak123** [comment]
Hi, I want to work on it as a participant in GSSOC'21, can you please assign this issue to me?

**Comment by abhinav5481** [comment]
Hello
I would like to work on this issue as part of GSSOC21. Could you please assign it to me?

**Comment by Esha-Sherring** [comment]
Hello
I would like to work on this issue as part of GSSOC21. Could you please assign it to me?

**Comment by Pranav016** [comment]
> @Pranav016 I would like to contribute.

Are you still working on this?

**Comment by nikhilgupta2001** [comment]
As a participant of GSSOC'21 ,I would like to contribute to it.
can u please assign it to me?

**Comment by SARVESHKHANDELWAL** [comment]
Hello, Can you please assign me?

**Comment by hrushikesh-git** [comment]
Hey @Pranav016 I love the idea and essence of the blogging site please assign this issue to me -GSSOC'21

**Comment by abhinav5481** [comment]
Hi,
I had created the PR. It was working as expected. May I know why I got unassigned to it?

**Comment by abhinav5481** [comment]
Regarding the small change in the URL variable, I think it's a small change, and I have completed it now.

**Comment by abhinav5481** [comment]
Please reassign it to me, otherwise, all my efforts would go into the vein

**Comment by Pranav016** [comment]
> Please reassign it to me, otherwise, all my efforts would go into the vain

I understand, but why wasn't there any response for 2-3 days.

**Comment by abhinav5481** [comment]
Hi,
I think there is a little bit of misunderstanding. After creating the PR you asked me to change the base branch and I immediately changed the base branch to develop. Then yesterday only you asked me to update the URL to old (process.env.url), I completed that today ( but till that time it got unassigned).
These were the changes that you asked me to do:
1. ![image](https://user-images.githubusercontent.com/60434542/111060234-5421fc00-84c1-11eb-8492-675e4fa23ea6.png)
I changed that immediately:
![image](https://user-images.githubusercontent.com/60434542/111060243-656b0880-84c1-11eb-889e-bf5bc8c47fa5.png)

2. Then yesterday you asked me to edit URL
![image](https://user-images.githubusercontent.com/60434542/111060253-829fd700-84c1-11eb-83f0-89d3e4a5928a.png)

Please let me know, which request I didn't respond to for 2-3 days.

**Comment by abhinav5481** [comment]
I have created another PR 13 minutes ago. That is still open. Should I now create another PR?
