### ISSUE TITLE
Add functionality to like blog posts.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#164]
### Feature request
Add functionality to like blog posts.

**Comment by luckykumarirai** [comment]
@Pranav016 I would like to work on it.

**Comment by luckykumarirai** [comment]
@Pranav016 I am not able to sign in to my local system, it sent some errors.
Due to this, I am not able to compose the blog. so any posts can not appear on my home page.
Then how I can test what I am changing?

**Comment by Pranav016** [comment]
> @Pranav016 I am not able to sign in to my local system, it sent some errors.
> Due to this, I am not able to compose the blog. so any posts can not appear on my home page.
> Then how I can be tested what I am changing?

What is the error ? Show screenshot of the error..

**Comment by luckykumarirai** [comment]
> > @Pranav016 I am not able to sign in to my local system, it sent some errors.
> > Due to this, I am not able to compose the blog. so any posts can not appear on my home page.
> > Then how I can be tested what I am changing?
> 
> What is the error ? Show screenshot of the error..

![Screenshot from 2021-02-15 22-00-27](https://user-images.githubusercontent.com/59636719/107975046-7ff2b480-6fdd-11eb-9774-6fd4a9e2e934.png)

**Comment by luckykumarirai** [comment]
whenever I click on the sign or sign-up button terminal automatically terminates and shows these errors.

**Comment by Pranav016** [comment]
Add a `.env` file in the main/ root folder.
The name of the file should be specifically `.env`.
Then just add
```
SECRET_KEY = "lucky"
```
to the `.env` file and it would work fine then 👍

**Comment by Pranav016** [comment]
> @luckykumarirai Add a `.env` file in the main/ root folder.
> The name of the file should be specifically `.env`.
> Then just add
> 
> ```
> SECRET_KEY = "lucky"
> ```
> 
> (it could be any string)
> to the `.env` file and it would work fine then 👍

Did this work or was it still giving error? @luckykumarirai

**Comment by luckykumarirai** [comment]
> > @luckykumarirai Add a `.env` file in the main/ root folder.
> > The name of the file should be specifically `.env`.
> > Then just add
> > ```
> > SECRET_KEY = "lucky"
> > ```
> > 
> > 
> > (it could be any string)
> > to the `.env` file and it would work fine then +1
> 
> Did this work or was it still giving error? @luckykumarirai

Yes, it is working but I am not able to add like functionality using node.js.

**Comment by Pranav016** [comment]
> Yes, it is working but I am not able to add like functionality using node.js.

It's ok 🙂

**Comment by vismitap** [comment]
Hey! I would like to work on this issue as a part of mexili winter of code. 😀

**Comment by Pranav016** [comment]
@vismitap Do you still want to work on this ? Since MWoC is over, let me know if you still want to work otherwise I'll change labels and open this issue to others as well.

**Comment by vismitap** [comment]
> @vismitap Do you still want to work on this ? Since MWoC is over, let me know if you still want to work otherwise I'll change labels and open this issue to others as well.

Please assign GSSOC label to it. I would like to work on this!

**Comment by vismitap** [comment]
Hey! The coding period starts from 8th March! Can I make a PR at that time?

**Comment by Pranav016** [comment]
> Hey! The coding period starts from 8th March! Can I make a PR at that time?

Wait, let me confirm, I thought it was 1 March.

**Comment by Pranav016** [comment]
> Hey! The coding period starts from 8th March! Can I make a PR at that time?

Are you still working on this?

**Comment by vismitap** [comment]
> > Hey! The coding period starts from 8th March! Can I make a PR at that time?
> 
> Are you still working on this?

Yes!

**Comment by AnanyaNegi** [comment]
> 
> 
> I would like to contribute to this issue is it open under GSSoc '21?

Thank you for your enthusiasm @anushree71199 . This issue is currently assigned to @vismitap . You may take a look at some other issues.

**Comment by AnanyaNegi** [comment]
/level2/
