### ISSUE TITLE
How to give the writer flexibility to add headings, bold words etc to make his/her blog better | Discussion issue

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#165]
## Description
How can we update our schema such that we are able to save headings and bold text or any font styles/ formatting's that can be used by the writer to make his/her blog look good.

**Comment by Ankita297** [comment]
can we use CKEditor plugin to provide the flexibility of writing format ?

**Comment by Pranav016** [comment]
> can we use CKEditor plugin to provide the flexibility of writing format ?

Yes, can you elaborate more about it? or give some reference links to it..

**Comment by Ankita297** [comment]
https://stackoverflow.com/questions/49596876/how-to-use-ckeditor-in-nodejs-application

**Comment by luckykumarirai** [comment]
@Pranav016 I have already integrated  ``` CKEditor```  in your project that provides full flexibility to change the style, insert images and make tables, Highlight the content.

https://user-images.githubusercontent.com/59636719/108625744-887e3b80-7472-11eb-9f4e-13c1f5558b54.mp4

Once it will approve then I will make PR.

**Comment by Pranav016** [comment]
> @Pranav016 I have already integrated ` CKEditor` in your project that provides full flexibility to change the style, insert images and make tables, Highlight the content.
> 
>  report.mp4 
> Once it will approve then I will make PR.

Looks good 👍  Yes. you can make a PR for this.
Since this is a discussion issue, raise a new issue for this and start working, I'll assign it.

**Comment by Pranav016** [comment]
Solved via #206
