### ISSUE TITLE
Make the input boxes look better and improve placeholder fonts.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#166]
### Is your feature request related to a problem? Please describe.
Make the input boxes look better and improve placeholder fonts.
![image](https://user-images.githubusercontent.com/54665036/107857103-5bb69c80-6e52-11eb-912d-7ab5182c8061.png)

### Describe the solution you'd like
Use better looking input boxes by styling them or using input boxes from any framework.

### Describe how this feature will be useful to our readers.
Improves user experience

**Comment by Devenkapoor7303** [comment]
Can I work on this Issue?

**Comment by Pranav016** [comment]
> Can I work on this Issue?

Which program do you want to contribute under? I'll add the appropriate labels

**Comment by Devenkapoor7303** [comment]
Cross Woc

**Comment by Pranav016** [comment]
> Cross Woc

I don't think this project is registered for Cross WoC. Let me know if you still want to work on this..

**Comment by Devenkapoor7303** [comment]
Yeah I will work on it

**Comment by archana-9430** [comment]
Please allow me to work on this .

**Comment by Pranav016** [comment]
> Please allow me to work on this .

Under which program will you be working under? I'll add appropriate labels.

**Comment by archana-9430** [comment]
I am working on this issue under GSSoC. Please add the appropriate labels (optional).

**Comment by archana-9430** [comment]
I am working on this issue under GSSoC. Please add the appropriate labels (optional).

**Comment by Pranav016** [comment]
> I am working on this issue under GSSoC. Please add the appropriate labels (optional).

Can't add them, development phase of GSSoC hasn't begun. You can work independently if you want to..

**Comment by archana-9430** [comment]
> > I am working on this issue under GSSoC. Please add the appropriate labels (optional).
> 
> Can't add them, development phase of GSSoC hasn't begun. You can work independently if you want to..

Okay, I'm ready to work on this independently.

**Comment by rishitbhojak** [comment]
@Pranav016 Can I work on this issue either under GSSoC or independently?

**Comment by Ankita297** [comment]
can i work on this ?

**Comment by rishitbhojak** [comment]
@Pranav016 Has the GSSOC label been added?

**Comment by Pranav016** [comment]
> > I am working on this issue under GSSoC. Please add the appropriate labels (optional).
> 
> Can't add them, development phase of GSSoC hasn't begun. You can work independently if you want to..

@rishitbhojak

**Comment by luckykumarirai** [comment]
I would like to contribute as participant of GSSOC.

**Comment by chehak123** [comment]
Hi, I want to work on it as a participant in GSSOC'21, can you please assign this issue to me?

**Comment by rishitbhojak** [comment]
Can you add the GSSoc'21 label?

**Comment by Pranav016** [comment]
> Can you add the GSSoc'21 label?

I have added the label for now, but make sure you are able to resolve the issue by tomorrow because you have already been assigned to this issue for 4 days. I advice not to retain an issue for more than 4-5 days then I'll assign the next person 👍

**Comment by rishitbhojak** [comment]
Yes. The work is almost done.  Will make the PR tomorrow

**Comment by innovation-platform** [comment]
Can I work on this?

**Comment by pi-squared-4** [comment]
I would love to work on this, please assign me this issue.

**Comment by abhishek7997** [comment]
Please assign this issue to me.

**Comment by innovation-platform** [comment]
![image](https://user-images.githubusercontent.com/65439306/110421601-d8d8d880-80c3-11eb-87de-226862c39d20.png)
Are the changes made fine or should I work on it more.

**Comment by innovation-platform** [comment]
I also have a small suggestion that it would be nice if we could increase the font size of the "Number of posts".

**Comment by Aanchal116** [comment]
Hii @Pranav016 , Can I please work on this issue as a part of GSSOC 21?

**Comment by lopamudra2000** [comment]
I want to work on enhancing these input fields and go buttons . Please assign it to me as a gssoc21 participant.
