### ISSUE TITLE
Make the navigation bar sticky at the top.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#167]

**Comment by pankajkumarbij** [comment]
I would like to work on this issue.

**Comment by pankajkumarbij** [comment]
@Pranav016 My marks for this issue is not reflected at JWOC leaderboard.

**Comment by Pranav016** [comment]
> @Pranav016 My marks for this issue is not reflected at JWOC leaderboard.

Ok, I'll look into it
