### ISSUE TITLE
Add CODE_OF_CONDUCT for the project.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#17]
# About issue-
Add a `CODE_OF_CONDUCT.md` file for the project.

**Comment by jackm9367** [comment]
@Pranav016 Working on finding an appropriate template. Feel free to assign me if you wish

**Comment by jackm9367** [comment]
#19

**Comment by Swapna804** [comment]
I would like to work on it

**Comment by djm-1** [comment]
May I work on this issue?

**Comment by Pranav016** [comment]
Are you still working on this? @djm-1

**Comment by tusharjain0022** [comment]
I would like to work on this
