### ISSUE TITLE
Add GirlScript Summer of Code to README

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#171]
### Feature request
Add GirlScript Summer of Code under `Open Source Events Project is associated with:` section in README.

**Comment by Ankita297** [comment]
can i work on this .

**Comment by Pranav016** [comment]
> can i work on this .

There is already an issue assigned to you, please resolve that first.

**Comment by Abhijay007** [comment]
can I work on this?

**Comment by Ankita297** [comment]
can i work on this now ?
