### ISSUE TITLE
Update demo gif in README

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#172]
### Feature request
Update the demo gif in the README so that new changes made to the website are displayed

**Comment by Abhijay007** [comment]
@Pranav016 Sir,  I would like to work on this issue

**Comment by Abhijay007** [comment]
@Pranav016 sir while making a gif for the readme I observe that the footer of the "compose" post section is not aligned properly at the bottom its has that same issue.

![compose](https://user-images.githubusercontent.com/64387054/107884825-08f5e700-6f1d-11eb-9301-6608aec325eb.PNG)


one thing I can do is that I will edit this locally and make a gif for the readme. 

ignore this if you already know about this bug.😅

**Comment by Abhijay007** [comment]
and sir can I solve these two issues (#171 and #172) in a single PR?

**Comment by Pranav016** [comment]
> and sir can I solve these two issues (#171 and #172) in a single PR?

Not advised, complete only the one you've been assigned.

**Comment by Pranav016** [comment]
> @Pranav016 sir while making a gif for the readme I observe that the footer of the "log-in" section is not aligned properly at the bottom its has that same issue.
> 
> ![compose](https://user-images.githubusercontent.com/64387054/107884825-08f5e700-6f1d-11eb-9301-6608aec325eb.PNG)
> 
> one thing I can do is that I will edit this locally and make a gif for the readme.
> 
> ignore this if you already know about this bug.😅

Don't worry, it is being worked on..

**Comment by Abhijay007** [comment]
@Pranav016 sir I made this gif:

![readme gif](https://user-images.githubusercontent.com/64387054/107886170-3d20d600-6f24-11eb-838e-d49cc83157ac.gif)

I tried to include that compose post section but I think that didn't work locally I need to do that from deployed version, but the problem with deployed version is that it already has some posts there which I think not look good in the display gif.

**Comment by Pranav016** [comment]
> @Pranav016 sir I made this gif:
> 
> ![readme gif](https://user-images.githubusercontent.com/64387054/107886170-3d20d600-6f24-11eb-838e-d49cc83157ac.gif)
> 
> I tried to include that compose post section but I think that didn't work locally I need to do that from deployed version, but the problem with deployed version is that it already has some posts there which I think not look good in the display gif.

I got your point, the deployed version's issue (footer) is currently being worked on. I am merging the footer PR right now so the deployed version will be corrected in a few mins then you can make a gif from that.

**Comment by Pranav016** [comment]
The deployed version has been fixed, you can make gif from that now. Don't worry about the displayed posts. They look fine. Just show all the functionalities of the website.

**Comment by Abhijay007** [comment]
@Pranav016 sir I have done with the gif part, I made three different GIFs with different time duration.
you can choose any gif out of those three. but as the size of the GIFs exceeds 10 MB I am not able to share the GIFs demo here.

So sir can I mail those GIFs or send you a message on your discord?

**Comment by Pranav016** [comment]
> @Pranav016 sir I have done with the gif part, I made three different GIFs with different time duration.
> you can choose any gif out of those three. but as the size of the GIFs exceeds 10 MB I am not able to share the GIFs demo here.
> 
> So sir can I mail those GIFs or send you a message on your discord?

GIFs are rarely greater than 10 MB unless they are really long, or they have very high frame rate. You can share it with me on discord or you can upload to google drive and share the link here. I don't think it should be this big in size, the one currently in the readme is 777KB (was optimized by img-bot) but even initially it was small in size. Since it the gif has to be stored in this GitHub repository itself hence try to keep the size small.

**Comment by Abhijay007** [comment]
first:https://giphy.com/gifs/WMafli0zJ3krDrK7d6

second: https://drive.google.com/file/d/1gLi0WJzQBKfeXkt7A-VJBxjvb_Aa32sW/view?usp=sharing

third:https://drive.google.com/file/d/16NnkbUCOz80gCFj9cRzQUEfs-5_LCQJK/view?usp=sharing

**Comment by Pranav016** [comment]
> first:https://giphy.com/gifs/WMafli0zJ3krDrK7d6
> 
> second: https://drive.google.com/file/d/1gLi0WJzQBKfeXkt7A-VJBxjvb_Aa32sW/view?usp=sharing
> 
> third:https://drive.google.com/file/d/16NnkbUCOz80gCFj9cRzQUEfs-5_LCQJK/view?usp=sharing

First one looks good :+1:

**Comment by Abhijay007** [comment]
> > first:https://giphy.com/gifs/WMafli0zJ3krDrK7d6
> > second: https://drive.google.com/file/d/1gLi0WJzQBKfeXkt7A-VJBxjvb_Aa32sW/view?usp=sharing
> > third:https://drive.google.com/file/d/16NnkbUCOz80gCFj9cRzQUEfs-5_LCQJK/view?usp=sharing
> 
> First one looks good 👍
> Also when you make the PR, delete the older git from assets folder.

ok @Pranav016 sir
