### ISSUE TITLE
Contributor's name not included in the contributor's list in the readme file.

### ISSUE THREAD

**Issue by aniketlodh** [ALPHAVIO/BlogSite#200]
### **Describe the bug**
My name is not listed in the contributor's list in the readme file even though I contributed and the PR was merged.

### **Expected behavior**
The expected behavior would be my name listed on the contributor's list in the readme file.

### **Screenshots**

![Screenshot from 2021-02-20 10-20-26](https://user-images.githubusercontent.com/55927827/108584195-65199a80-7365-11eb-87de-f2611b9efa42.png)
![Screenshot from 2021-02-20 10-21-05](https://user-images.githubusercontent.com/55927827/108584197-664ac780-7365-11eb-897d-713c561329db.png)

**Comment by Pranav016** [comment]
Resolved #201
