### ISSUE TITLE
Make dark mode persist while changes pages

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#216]
# Feature request-
Make dark mode persist on different pages for logged in users.

# Current Behavior-
Dark mode doesn't stay on changing the page like going to about page or contact etc.

# Expected Behavior after this issue-
Dark mode persists between the pages for logged in users, until switched back to light mode.

**Comment by vismitap** [comment]
Hey! I would like to work on this issue!

**Comment by Pranav016** [comment]
> Hey! I would like to work on this issue!

Please mention under which program would you like to work on this..
If you are a part of GSSoC, points won't be given on issues/ PRs before 1 March.

**Comment by vismitap** [comment]
> > Hey! I would like to work on this issue!
> 
> Please mention under which program would you like to work on this..
> If you are a part of GSSoC, points won't be given on issues/ PRs before 1 March.
under mexili
