### ISSUE TITLE
Add functionality to delete blog posts.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#22]
# About issue-
- Add a delete button on each post.
- The button should have a post request that should delete the blog from the database.

**Comment by sahilsaha7773** [comment]
I would like to work on this

**Comment by mak-ux** [comment]
Let me work on this issue, I mean when you will open front 21

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue as a mentee of JWOC.
