### ISSUE TITLE
I would like to work on the frontend using React JS

### ISSUE THREAD

**Issue by A7abhilash** [ALPHAVIO/BlogSite#221]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 

### Describe the solution you'd like
I have already made a similar project, do check it out [Blogchord](https://github.com/A7abhilash/blogchord). If you would like to move on from EJS to a better frontend technology then I would like to work on frontend part using React JS and build a neat UI using bootstrap and framer motion. We can get started with basic features to be added and as we move on, we can add more features.

### Describe alternatives you've considered
I would like to go with the design that the mentor would like to have. 

### Describe how this feature will be useful to our readers.
UI is the most important thing that attracts the readers and the UI of current website must be improved a lot.

### Additional context

#GSSOC21

**Comment by Pranav016** [comment]
Sure, You can work on this issue. You can start by implementing a similar frontend using React. Later we can add more features.

**Comment by mansijain980** [comment]
@Pranav016 Sir , we can add more features in this like we can use node.js for blog updation.

**Comment by Pranav016** [comment]
> @Pranav016 Sir , we can add more features in this like we can use node.js for blog updation. I have read contributing guidelines and like to work on it .
> Please assign me this .

Yes, we can add more features. This issue was raised by @A7abhilash and he is working on making the frontend using React. This one is currently assigned to him. You can raise a new issue with whatever feature you want to implement or check out other open issues to contribute 👍

**Comment by AnanyaNegi** [comment]
/level3/

**Comment by lopamudra2000** [comment]
I want to contribute along to refractor the current structure in to React. I am a gssoc21 participant . please assign this to me

**Comment by lopamudra2000** [comment]
I want to contribute along to refractor the current structure in to React. I am a gssoc21 participant . please assign this to me

**Comment by AnanyaNegi** [comment]
@lopamudra2000 are you willing to work on this issue?

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...

**Comment by A7abhilash** [comment]
@ShambhaviSharma0110 I have already done the work on hosted it also for the [demo](https://blogsite-frontend-dev.netlify.app/).
But I'm not able to get the auth token after sign in/sign up. Idk why but it was perfectly fine in localhost.
Do u have any idea why it could be so?
[Repo of revamped app](https://github.com/A7abhilash/BlogSite/tree/develop)
