### ISSUE TITLE
Update the GIF in the README

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#223]
Update the GIF in the README to show the current website.

**Comment by Ankita297** [comment]
I would like to work on this ? 
Can you Please add the GGSoC label ?

**Comment by Ankita297** [comment]
I would like to work on this .
Can you please add the GSSoC label ?

**Comment by Ankita297** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/67833077/109753951-27403000-7c09-11eb-8006-8ce5672decf7.gif)

**Comment by Ankita297** [comment]
Sir is it okay ?

**Comment by Pranav016** [comment]
> Sir is it okay ?

Looks good.

**Comment by Ankita297** [comment]
![Comparing ALPHAVIO_develop Ankita297_gif-new · ALPHAVIO_BlogSite - Google Chrome 04-03-2021 08_54_12](https://user-images.githubusercontent.com/67833077/109907013-7c427b80-7cc7-11eb-8ffd-6596813657b2.png)
![Comparing ALPHAVIO_develop Ankita297_gif-new · ALPHAVIO_BlogSite - Google Chrome 04-03-2021 08_54_21](https://user-images.githubusercontent.com/67833077/109907020-7fd60280-7cc7-11eb-8d63-7b8784e457f7.png)

**Comment by Ankita297** [comment]
Sir what should i do in this ? it is showing all the commits ?

**Comment by Ankita297** [comment]
But if i compare gif-new with your master branch then it will show only one commit .
