### ISSUE TITLE
Add categories feature for the blogs.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#224]
### Feature request
* Allow the author of the blogs to choose a category (from a dropdown menu of categories) when he is creating a blog post. This will be stored in the DB so some alteration to the schema will be required.
* Allow user to search via categories by giving a dropdown menu of categories on the home page.

**Comment by tanay13** [comment]
@Pranav016 please assign this to me

**Comment by tanay13** [comment]
@Pranav016 Please assign this to me

**Comment by Pranav016** [comment]
Categories can be seen in #225

**Comment by A7abhilash** [comment]
@Pranav016 I'll add this feature also once I'm done with frontend using ReactJS

**Comment by Pranav016** [comment]
> @Pranav016 I'll add this feature also once I'm done with frontend using ReactJS

You can work on this after the other one gets merged. Also if you are done with that, you can make a PR, reviewing takes time.

**Comment by A7abhilash** [comment]
@Pranav016 yeah sure sure... Im working on all the [features](https://github.com/A7abhilash/blogchord/blob/dev/README.md) and ill try hosting it so that you can have a look at it before merging and sugfest any changes(UI, functioning and a bit of animations) ... Once its meged then we can go ahead with the additional features that are mentioned in issues list

**Comment by subhangi2731** [comment]
can you please assign this to me?

**Comment by Pranav016** [comment]
> can you please assign this to me?

You want to work under GSSoC ?

**Comment by dhruvinfo28** [comment]
Shall I work on this under GSSoc 2021? I will use EJS templating engine.

**Comment by anushree71199** [comment]
Can I contribute to this issue under GSSoc '21?

**Comment by AnanyaNegi** [comment]
/level3/

**Comment by AnanyaNegi** [comment]
@A7abhilash  are you still working on this issue?

**Comment by A7abhilash** [comment]
> @A7abhilash are you still working on this issue?

I have already implemented this feature while I was revamping frontend with react... But unfortunately in production, frontend is not able to get the authenticated token back from backend... IDK why so, I am just wandering around that bug....
