### ISSUE TITLE
Deciding the categories for the bogs || Discussion issue

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#225]
I wanted everyone's opinion on what are the different categories that we should divide/ separate the blogs under.
This discussion is in correspondence to the issue #224 .

**Comment by ankitbiswal547** [comment]
Hey There! 
I would Like to suggests some categories.
Here they are:

1. IT & Software
2. Business
3. Personality Development
4. Design
5. Marketing
6. Lifestyle
7. Photography
8. Health & Fitness
9. Music
10. Academics
11. Language
12. sports
13. social media
14. History
15. space and research

**Comment by Pranav016** [comment]
@ankitbiswal547  Thank you for all the suggestions, these will be really useful.

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by Pranav016** [comment]
> can you please assign this issue to me?

This is just a discussion, issue to decide categories for #224 , you can work on some other issue..
