### ISSUE TITLE
adding  update option on each post 

### ISSUE THREAD

**Issue by bitaashna** [ALPHAVIO/BlogSite#228]
1.Add update option on post.Author of the post can update the post

I would like to work on it as a part of **GSSOC'21**
Can you please assign this work to me.

**Comment by Rimpi246** [comment]
I would like to work on this issue.Please `/assign` this to me as a part of GSSOC'21

**Comment by Riya764** [comment]
I would like to work on this issue.Please assign this to me as a part of GSSOC'21

**Comment by nikhilgupta2001** [comment]
I would like to work on this issue.Please assign this to me as a part of GSSOC'21

**Comment by aniketlodh** [comment]
Delete function on each post is already added. The feature is, the author of the post can only delete the post.

**Comment by Rimpi246** [comment]
And update also after editing

**Comment by aniketlodh** [comment]
Hi @Pranav016,  i would like to work on this issue.

**Comment by aniketlodh** [comment]
Hello @Pranav016, Can you please tell me whether I can start working on this issue?

**Comment by AnanyaNegi** [comment]
> 
> 
> Hello @Pranav016, Can you please tell me whether I can start working on this issue?

Yes. You can start working. I've already assigned you the issue.
