### ISSUE TITLE
Margin under nav-bar

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/BlogSite#232]
### **Describe the bug**
Some bottom margin is needed under the navbar. It looks pretty bad as of now.

### **To Reproduce**
1. Go to https://blogsite321.herokuapp.com/
2. See error

### **Screenshots**
![image](https://user-images.githubusercontent.com/56315878/110336884-4f85bf80-804b-11eb-9919-453edc9f3efa.png)

### **Additional context**
Would like to work on it under GSSOC' 21.

**Comment by nandini7637** [comment]
Hello I would like to contribute to it being a part of GSSOC, please assign it to me.

**Comment by abhishek7997** [comment]
Please assign this issue to me. I wish to contribute to it as a participant of GSSOC 2021

**Comment by abhishek7997** [comment]
![image](https://user-images.githubusercontent.com/68701271/110372958-f3379580-8074-11eb-89df-ea6e9fea5ba5.png)
Is this margin good enough?
Can I merge it?

**Comment by abhishek7997** [comment]
Sir, I have successfully made a PR, what will happen next?

**Comment by cryptofox17** [comment]
I would like to work on this issue, please consider assigning it to me

**Comment by Aanchal116** [comment]
Hello I would like to contribute to it being a part of GSSOC, please assign it to me.

**Comment by hrushikesh-git** [comment]
Hey wanted to work on this issue as the
 beginning of my GSSOC'21 contribution

**Comment by satcasm** [comment]
Closing the issue as PR is merged.
