### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/BlogSite#234]
The text color used in the paragraph with ``class=content-body-font`` just under the navbar is getting mixed up with the background  which doesn't looks so good.

Would like to improve upon it as a part of GSSOC' 21.

**Comment by GuptaTanisha** [comment]
Can I work on this?

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by micksharma** [comment]
Can I work on this issue ?

**Comment by NehaK745** [comment]
Can l work on this issue?

**Comment by sahildotexe** [comment]
Can you assign this issue to me?

**Comment by Riya764** [comment]
Can l work on this issue?

**Comment by Aditya7494** [comment]
I am interested in contributing to fix this issue.
Can you please assign to me?

**Comment by Sakshi0401** [comment]
can you please assign this issue to me?

**Comment by Naman-12911** [comment]
hello,
can you please assign me this issue under GSSOC

**Comment by Ayushisood** [comment]
Hii @Pranav016 
I would love to contribute to this task as a GSSOC'21 participant.
Kindly assign the task to me as i am very much familiar with HTML,CSS, JS.

**Comment by SARVESHKHANDELWAL** [comment]
Hola @Pranav016,
Can you please assign me this issue?

**Comment by AasthaCodex** [comment]
hey @Pranav016 Can you please assign this issue to me?

**Comment by satyabhagavan** [comment]
Hey @Pranav016 
As a GSSOC'21 participant I would love to work upon this issue. I have previously worked with HTML, CSS, React JS as well as Bootstrap. Could you please assign this issue to me?
Thank you!!

**Comment by pshivesh8** [comment]
As a GSSOC'21 participant, I would love to work on this issue. I have previously worked with HTML, CSS, React JS, Node JS as well as Bootstrap. Could you please assign this issue to me?
Thank you!!

**Comment by Asmita-si** [comment]
I want to work on this issue. Can you please assign it to me? @Pranav016

**Comment by simranbhalla3** [comment]
Please assign this issue to me, i would like to work on this and show my creativity @Pranav016

**Comment by satcasm** [comment]
Closing this issue as PR is merged.
