### ISSUE TITLE
Add GitHub action to automatically close issue if it's corresponding PR gets merged.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#235]
# Feature request-
Add GitHub action to automatically close issue if it's corresponding PR gets merged. If the issue is mentioned in a PR and it gets merged then sometimes doesn't close automatically so add a GH action for that.

Note: If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.

**Comment by Ankita297** [comment]
https://github.com/marketplace/actions/closes-issues-related-to-a-merged-pull-request

**Comment by Ankita297** [comment]
Sir are you asking about something  like this ?

**Comment by Pranav016** [comment]
> Sir are you asking about something like this ?

Yes this works..

**Comment by Ankita297** [comment]
okay sir.

**Comment by Ankita297** [comment]
So we have to include both master and develop branch or only develop ?

**Comment by Ankita297** [comment]
So can you assign me this again ?
