### ISSUE TITLE
Add GitHub action to automatically add label

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#237]
# Feature request-
Add GitHub action to automatically add `GSSoC'21` label if `GSSoC` or `GSSoC'21` or `GSSoC '21` is mentioned anywhere in an issue body.

Note: If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
Then you can directly start working on it.

**Comment by PHAGUN-JAIN** [comment]
hey! i would like to work on this as a GSSOC'21 participant

**Comment by micksharma** [comment]
Can I work on this issue as a Gssoc 2021 participant ?

**Comment by Pranav016** [comment]
> Can I work on this issue as a Gssoc 2021 participant ?

Read the note in the issue description!

**Comment by Pranav016** [comment]
/level2/
