### ISSUE TITLE
Like feature 

### ISSUE THREAD

**Issue by Rimpi246** [ALPHAVIO/BlogSite#243]
### There is no number of views feature in the blogs
There should be a number of views feature to keep count of how many people visited your blog

### Please  `/assign` this to me.I would like to work on it as a part of GSSOC'21.

<hr/>

**Comment by Riya764** [comment]
would like to work on this under gssoc'21.

**Comment by anushree71199** [comment]
I would like to work on this issue under GSSoc '21

**Comment by Pranav016** [comment]
Is this issue repeat of #244 or #164 .
If yes then you can close this issue :)
otherwise you can explain what you want to work under this..

**Comment by Pranav016** [comment]
Closing for now, re-raise issue if required
