### ISSUE TITLE
Number of views feature

### ISSUE THREAD

**Issue by Rimpi246** [ALPHAVIO/BlogSite#244]
### There is no number of views feature
There should be a number of views feature to help keep count of how many people visited your blog.

### Please `/assign` this to me as a part of GSSOC'21

<hr/>

**Comment by aniketlodh** [comment]
I would like to work on the number of views feature.

**Comment by Rimpi246** [comment]
Hello @Pranav016 , this is not the same as the like functionality issue. This feature is to give a count of how many people visited your blog. Hope that makes it clear😃
Hence if you think this as acceptable, I would like to work on this. So please assign this to me

**Comment by AnanyaNegi** [comment]
/level2/

**Comment by AnanyaNegi** [comment]
Hi @Rimpi246 Are you still working on this issue?

**Comment by Rimpi246** [comment]
Ya.. I am working on it

**Comment by aniketlodh** [comment]
@Rimpi246 are you still working on this issue?

**Comment by Rimpi246** [comment]
Yeah yeah..I am working.Please bear with me.

**Comment by AnanyaNegi** [comment]
> 
> 
> Yeah yeah..I am working.Please bear with me.

Hi @Rimpi246 .It has been 4 days since your last update and I don't see any PR regarding this issue from your side. Is the issue still being worked upon?

**Comment by Rimpi246** [comment]
Hello @AnanyaNegi I was facing problems because of  another problem which I have told in discord and @Pranav016 told me to raise it as an issue. I have solved that issue and so working on this issue.. I want a little more time. Thank you

**Comment by AnanyaNegi** [comment]
> 
> 
> Hello @AnanyaNegi I was facing problems because of another problem which I have told in discord and @Pranav016 told me to raise it as an issue. I have solved that issue and so working on this issue.. I want a little more time. Thank you

Sure. No problem.

**Comment by AnanyaNegi** [comment]
@Rimpi246  status?

**Comment by aniketlodh** [comment]
Hi @Rimpi246, are you still working on this issue?

**Comment by Rimpi246** [comment]
@aniketlodh , I have partially solved the issue.. Just solving a minor bug

**Comment by aniketlodh** [comment]
@Rimpi246 Can you please tell how long it would take?

**Comment by Rimpi246** [comment]
I am sending a pr now

**Comment by aniketlodh** [comment]
Hey @Pranav016, Can I work on this issue if the assignee is facing some problem solving the issue or if she is unable to solve it? I think I can solve the issue. I'm also a GSSOC participant.

**Comment by aniketlodh** [comment]
Thanks @Pranav016 for assigning me the issue. I'm starting to work on this.

**Comment by aniketlodh** [comment]
On which branch should I generate the PR? master or deploy?

**Comment by Pranav016** [comment]
> On which branch should I generate the PR? master or deploy?

Master, wait till login issue gets resolved

**Comment by aniketlodh** [comment]
Hey @Pranav016 , can you please tell if the login issue has been solved so that i can generate the PR for number of views?

**Comment by Pranav016** [comment]
> Hey @Pranav016 , can you please tell if the login issue has been solved so that i can generate the PR for number of views?

Yes fixed
