### ISSUE TITLE
Font is not clearly visible on the Blog page.

### ISSUE THREAD

**Issue by ishikalohia** [ALPHAVIO/BlogSite#249]
On the Blog page , the font size is too small. It is not clearly visible and the font color is similar to the background image which makes it difficult for the user to read.

![image](https://user-images.githubusercontent.com/58163099/110454778-acd24d00-80ed-11eb-8c38-807e7d6d3a0a.png)

I would like to work on the blog page and make it look more attractive and readable for the users. 

Can you assign this issue to me under GSSOC21.

**Comment by ishikalohia** [comment]
`/assign`

**Comment by shudhanshu03** [comment]
/gssoc/

**Comment by shudhanshu03** [comment]
/level2/

**Comment by Nirpendra09** [comment]
I want to work on this.

**Comment by Nirpendra09** [comment]
Please assign me this task

**Comment by Nirpendra09** [comment]
Please assign me this task

**Comment by RushanKhan1** [comment]
@ishikalohia @kanchi-22 @mohdjameel2412 @ambivert-sam The website has gone through major frontend changes and I think this issue has been by and large fixed. Hence I'm closing this issue.
