### ISSUE TITLE
Add a contact form

### ISSUE THREAD

**Issue by mis-coder** [ALPHAVIO/BlogSite#252]
### Is your feature request related to a problem? Please describe.
  Not a problem actually, rather an improvement I will say. In the Contact Us page, a form can be added.

### Describe the solution you'd like
- So we can add a form with fields, like name, email, message and a submit button which is what a usual form has. 

### Describe alternatives you've considered
- Even if you don't want to have extra work, we can also add a google form, which I think is also a good solution.

### Describe how this feature will be useful to our readers.
      I think that will be more easy for users rather than redirecting them to some other site or page for saying what they want to say.
<hr/>
 And I would love to work on this thing.

**Comment by RushanKhan1** [comment]
/gssoc/

**Comment by RushanKhan1** [comment]
/level2/
