### ISSUE TITLE
Modify SignUp and Login input fields.

### ISSUE THREAD

**Issue by ireneelizabethsabu** [ALPHAVIO/BlogSite#259]
### Is your feature request related to a problem? Please describe.
yes, The input fields in the signup and login page are too long which doesn't look good for the webpage.

### Describe the solution you'd like
So the width can be reduced to a half and properly aligning the section to center.

### Describe how this feature will be useful to our readers.
It will give a more comfortable look to the website.

### Additional context
![Screenshot from 2021-03-10 10-26-00](https://user-images.githubusercontent.com/56963461/110579406-c24a8400-818c-11eb-9288-6855bb378418.png)

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by abhishek96k** [comment]
Please /assign me this issue as a part of GSSoC'21

**Comment by shudhanshu03** [comment]
/level2/

**Comment by RushanKhan1** [comment]
@ireneelizabethsabu Hey! It has been a long time since you were assigned this issue therefore I am assigning this issue to someone else.

**Comment by RushanKhan1** [comment]
@ambivert-sam I am assigning this issue to you, all the best. Please make the pr within the allotted time which is 4 days for a level 2 issue.

**Comment by ambivert-sam** [comment]
Hey @RushanKhan1 you can assign to someone else as I can't devote much time due to my prior commitment, sorry!

**Comment by Sandi-09** [comment]
can i work on this issue

**Comment by Mus2413** [comment]
Hello, I am Gssoc'21 participant . I would like to contribute on this project. Could you please assign me this issue.

**Comment by Aayu231** [comment]
Hi, I would like to work on this issue under GSoC'21.

/assign

**Comment by RushanKhan1** [comment]
@Sandi-09 Sure, I am assigning this issue to you. You have 4 days to complete it. All the best!
