### ISSUE TITLE
Fix Common URLs for different posts with same name.

### ISSUE THREAD

**Issue by RushanKhan1** [ALPHAVIO/BlogSite#264]
### **Describe the bug**
The URL for posts is not unique, which results in a conflict for posts with the same name. If there are multiple posts with the exact same name, then the post which is the oldest will be opened every time when you click on ``Read More`` on any of the same name posts.

### **To Reproduce**
1. Go to the [project website](https://blogsite321.herokuapp.com/).
2. Create an account or log in.
3. Compose 2 posts with the exact same name but with different body contents.
4. Click ``Read More`` on the newer post of the two.
5. Notice how you have been redirected to the other post with the same name.

### **Expected behavior**
Ideally, the website should have a unique URL for every post, even for posts with the same name. So that the user gets correctly redirected to the post that he clicks on.

### **How to proceed**
* Currently the express route parameters for ``posts/:postName`` takes ``postName`` which is the post's title as the argument which can be common between posts.
* Instead, try to give the **post id** as the argument to the route parameter since MongoDB maintains a unique id for every post therefore it will make our URL unique.

**Hint:** Look into how the posts are rendered in ``/views/home.ejs``.

**Comment by prajjwalarora** [comment]
@Pranav016 I want to work on this issue under GSSOC21. can you please assign this to me?

**Comment by AnanyaNegi** [comment]
/level2/
