### ISSUE TITLE
Want to add some functionalities

### ISSUE THREAD

**Issue by Siddharth1006** [ALPHAVIO/BlogSite#265]
1) want to add a functionality to get notified when a user I followed posted so that I can read.
2) Would like to add a functionality to SAVE a particular post of another user so that i can read later.

**Comment by Siddharth1006** [comment]
I want to work on this issue as a GSSOC'21 participant.

**Comment by nishantsahu961** [comment]
I would like to work upon the addition of these feature  as a GSSOC 21 participant

**Comment by AnanyaNegi** [comment]
/gssoc/

**Comment by AnanyaNegi** [comment]
/level3/

**Comment by RushanKhan1** [comment]
@Siddharth1006 Hey, did you make any progress? Also, I want to know how do you plan to implement your 1st feature considering that we don't have a user profile page just now?

**Comment by Inventor77** [comment]
@RushanKhan1 @AnanyaNegi  Please Mentor can I be Assigned on this Issue

**Comment by Pranav016** [comment]
create separate issues for both of these functionalities..
