### ISSUE TITLE
Organising the code first

### ISSUE THREAD

**Issue by Abhinaba006** [ALPHAVIO/BlogSite#266]
### Is your feature request related to a problem? Please describe.
It is a feature request, mainly in the code part. I will work under GSSOC

### Describe the solution you'd like
I will organize the files and the code that will make it easy to read and that will be helpful for future editing. for example the blog model is not in the model directory instead it is in the index.js and there are many this type of problems, so I will first like to organize the code and then add new features also I will like change the design a little bit so the website can be more attractive and easy to use.

### Describe how this feature will be useful to our readers.
It will mainly for the other developer working in this project, it will be very easy if the codes are clean and well organized. It will be helpful for others.

**Comment by Abhinaba006** [comment]
@RushanKhan1 , I have written what I will like to do, after this I will add more features to this website. Can you kindly add a gssoc21 label to this bug as I am working under gssoc21, it will be helpful for me

**Comment by RushanKhan1** [comment]
Okay, but I suggest you make different issues and pull requests for different features/fixes. This will help us add relevant tags on all the issues and pull requests and will make it easier for us to decide which pull request needs to be merged. So for this issue, I suggest you primarily work on code restructuring, and create different issues and pull requests for the other things you mentioned.

**Comment by RushanKhan1** [comment]
/gssoc/

**Comment by Abhinaba006** [comment]
Yes, understood, I have done the restructuring well so I am sending the pr now and later I will create more issues to add features.

**Comment by Abhinaba006** [comment]
/level1/

**Comment by Abhinaba006** [comment]
/reviewed/
