### ISSUE TITLE
Change color theme of the full website.

### ISSUE THREAD

**Issue by FireQueen-3010** [ALPHAVIO/BlogSite#268]
### **Describe the bug**
The theme of the website is not particularly impressive. The color themes (including fonts, buttons, footers, and various sections of the website) are not exactly appealing.

### **To Reproduce**
1. Fork and clone the project.
2. Create a new branch because changing the full theme is a major change.
3. Go to the 'public' folder of the project.
2. Open the CSS folder.
3. Open the style.css file
4. Set a well-defined color theme.
5. Start working on the code and changes.

### **Expected behavior**
The website would turn out to be visually appealing to every person who visits the site.

### **Additional context**
The goal is to beautify the website by giving it a definite color theme.

**Comment by AnanyaNegi** [comment]
/level1/

**Comment by AnanyaNegi** [comment]
/gssoc/

**Comment by FireQueen-3010** [comment]
Hi Ananya, thank you so much for assigning this issue to me. I have a tiny doubt, please do clarify it. Changing the entire theme in the website is a major feature that changes the complete look and feel of the website and it takes a bit of work as well. Do you think, it would be worth increasing the issue's level? Hope you consider this and I will glad whatsoever would be your decision. Thank you again!

**Comment by AnanyaNegi** [comment]
Sure @FireQueen-3010  ill be raising the level of the issue to `level 2`. Hope that's okay with you. Thank you for bringing this to my attention.

**Comment by AnanyaNegi** [comment]
/level2/

**Comment by FireQueen-3010** [comment]
Thank You!

**Comment by FireQueen-3010** [comment]
Hi @AnanyaNegi can we connect on discord, I have a few questions regarding the issue related to npm and MongoDB as I am facing an issue in displaying them in my local host.

**Comment by AnanyaNegi** [comment]
> 
> 
> Hi @AnanyaNegi can we connect on discord, I have a few questions regarding the issue related to npm and MongoDB as I am facing an issue in displaying them in my localhost. My discord id: Diksha(p)

Sure.

**Comment by FireQueen-3010** [comment]
Do we have a discord server for BlogSite if not how do I ping you? @AnanyaNegi

**Comment by sahilempire** [comment]
I want to work on this issue, **Please assign me** as a **GSSoC'21 participan**t.

Thank you.

**Comment by FireQueen-3010** [comment]
I've pinged you on discord, please check @AnanyaNegi

**Comment by AnanyaNegi** [comment]
@FireQueen-3010 are you still working on this issue?

**Comment by FireQueen-3010** [comment]
Yes I am please give me a couple more days

**Comment by AnanyaNegi** [comment]
> 
> 
> Yes I am please give me a couple more days. Two more days that's it

Okay. No problem. when you are done create a pr, I'll review it.

**Comment by manognyaa** [comment]
Can I also contribute to this issue ? @AnanyaNegi

**Comment by AnanyaNegi** [comment]
> 
> 
> Can I also contribute to this issue ? @AnanyaNegi

Hi @manognyaa .This issue is currently assigned to @FireQueen-3010 .You may open a new issue or take a look at some other pre-existing ones.
