### ISSUE TITLE
Third Party Authentication

### ISSUE THREAD

**Issue by krishna-y2000** [ALPHAVIO/BlogSite#269]
### Is your feature request related to a problem? Please describe.
I have found that  3rd party authentication is remaining to add in this project . It is very helpful nowadays and saves a lot more time . 

### Describe the solution you'd like
I would like add direct authentication api of google and facebook in this project so that user's time will save.

Let me build this feature and assign  this task to me as part of gssoc'21.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by AnanyaNegi** [comment]
/gssoc/

**Comment by AnanyaNegi** [comment]
/level3/

**Comment by krishna-y2000** [comment]
@AnanyaNegi mam, I am working on this issue. I should continue my work,right ? I am confused you closed it earlier and now opened ? Do reply please.

**Comment by AnanyaNegi** [comment]
> @AnanyaNegi mam, I am working on this issue. I should continue my work,right ? I am confused you closed it earlier and now opened ? Please reply .

@krishna-y2000 this issue is still open. That was some other issue #293 which was closed because it was similar to this one. However can you state the progress of your task?

**Comment by krishna-y2000** [comment]
> > @AnanyaNegi mam, I am working on this issue. I should continue my work,right ? I am confused you closed it earlier and now opened ? Please reply .
> 
> @krishna-y2000 this issue is still open. That was some other issue #293 which was closed because it was similar to this one. However can you state the progress of your task?

Sure. I studied how google strategy works and how password is used to authenticate api. I am in mid way of google-strategy in coding part. It will be completed in few days.

**Comment by krishna-y2000** [comment]
@AnanyaNegi  Hii,
I have done the backend part but there is need to do some modification in the code . Like , when i authenticate with google oauth it leads to frontend without changing the ```log-in``` button which is at top-right  to ```log-out``` . I have even generated jwt token .
[Link to my remote branch](https://github.com/krishna-y2000/BlogSite.git)
go to 269-issue branch . My changes are in user.router.js and index.router.js file .
Please have a look and give suggestions .Thanks.
@Pranav016

**Comment by Pranav016** [comment]
> @AnanyaNegi Hii,
> I have done the backend part but there is need to do some modification in the code . Like , when i authenticate with google oauth it leads to frontend without changing the `log-in` button which is at top-right to `log-out` . I have even generated jwt token .
> [Link to my remote branch](https://github.com/krishna-y2000/BlogSite.git)
> go to 269-issue branch . My changes are in user.router.js and index.router.js file .
> Please have a look and give suggestions .Thanks.
> @Pranav016

You haven't filled req.user with the user information that is why it still shows login event after you sign in..
Check index router's `isAuthenticated` field you'll get
Make a middleware for that

**Comment by Pranav016** [comment]
Wait, we implemented login using jwt, will passport google auth work ? it is not creating any token so how would it change, and you didn't even export or import your passport file anywhere..

**Comment by krishna-y2000** [comment]
Yes , that is the problem about token . In auth file there is token created by using id  and userName which will not work for google oauth as there no property of custom userName in google oauth.

**Comment by Pranav016** [comment]
> Yes , that is the problem about token . In auth file there is token created by using id and userName which will not work for google oauth as there no property of custom userName in google oauth.

Try searching auth in her then

**Comment by krishna-y2000** [comment]
We can create authentication using password-jwt along with google , facebook oauth and which seems easy and flexible . 
[Have a look at this blog](https://medium.com/@rustyonrampage/using-oauth-2-0-along-with-jwt-in-node-express-9e0063d911ed)
i have to re-write the code for it but it seems good . Otherwise i will try to sync the current one if possible. What do you say ?  
Also ,it would be good if user login using email and password rather than userName and password.
