### ISSUE TITLE
[GSSOC'21] Confirm password text box is not present

### ISSUE THREAD

**Issue by krishna-y2000** [ALPHAVIO/BlogSite#270]
### Is your feature request related to a problem? Please describe.
Sometimes user urgently enter wrong password during sign up and forget that . Confirm password will help them to write it twice so they will not forget and also write it correctly.

### Describe the solution you'd like
I would like to add a new text box in sign up that will match the current password and also will make changes to backend with smooth code.

Please assign this task to me .
Contributing as a GSSOC'21 partcipant.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by krishna-y2000** [comment]
\assign

**Comment by shudhanshu03** [comment]
/gssoc/ 
/level2/

**Comment by shudhanshu03** [comment]
/level2/

**Comment by RushanKhan1** [comment]
@krishna-y2000, It's been 7 days since you were assigned the issue that's 3 more days than the time allotted for level2 issues, are you still working on it?

**Comment by krishna-y2000** [comment]
@RushanKhan1  sir , 
FOA sorry for delay and thanks for your patience, i was completing my college work as soon as possible . yesterday i got free. This will get completed by till tomorrow .Thanks
