### ISSUE TITLE
All models should be under model folder

### ISSUE THREAD

**Issue by Abhinaba006** [ALPHAVIO/BlogSite#282]
### Is your feature request related to a problem? Please describe.
The blog mongoose model is in the app.js and the user model is in the model folder, which is very uncomfortable to read for developers, I want to fix that issue.

### Describe the solution you'd like
transfer the blog model under the model folder

### Describe alternatives you've considered
need no alternatives.

### Describe how this feature will be useful to our readers.
It will be useful for developer cause it makes the code easy to read and understandable.

### Additional context

<hr/>
I am a gssoc21 participant, I will like to work for this project.
Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by RushanKhan1** [comment]
/gssoc/

**Comment by RushanKhan1** [comment]
/level2/
