### ISSUE TITLE
Adding a auto Page Scrolling Button.

### ISSUE THREAD

**Issue by SpecTEviL** [ALPHAVIO/BlogSite#285]
### Is your feature request related to a problem? Please describe.
When there are many blogs the webpage becomes lengthy and thus if the user is at the bottom and wants to go on top then they need to scroll a lot.

### Describe the solution you'd like
During such scenarios, the auto page scrolling button comes in handy allowing the user to scroll to the top just with the help of a single button.

### Describe alternatives you've considered
A auto-scrolling button to the bottom right of the page beside the chatbot.

### Describe how this feature will be useful to our readers.
With the help of this auto-scrolling button, the user won't have to scroll manually to go to the top of the page thus improving the UX of the site.

### Additional context
For reference, you can see the one I have on my portfolio https://spectevil.github.io in the right bottom corner.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by SpecTEviL** [comment]
As this issue is under GSSoC'21 I request the admins @Pranav016 to add a GSSoC tag and a difficulty level accordingly.
Thanks!

**Comment by RushanKhan1** [comment]
/gssoc/

**Comment by RushanKhan1** [comment]
/level2/

**Comment by RushanKhan1** [comment]
@SpecTEviL Hi, It has been 6 days since you were assigned the issue, that's 2 more days than the time allotted for leve2 issues. Are you still working on it?

**Comment by SpecTEviL** [comment]
> @SpecTEviL Hi, It has been 6 days since you were assigned the issue, that's 2 more days than the time allotted for leve2 issues. Are you still working on it?

Yes, the implementation is done, it's just that I'm facing some errors and I'm debugging them. 
Can you just give me an extension of one more day, please?
Thanks!

**Comment by RushanKhan1** [comment]
> > @SpecTEviL Hi, It has been 6 days since you were assigned the issue, that's 2 more days than the time allotted for leve2 issues. Are you still working on it?
> 
> Yes, the implementation is done, it's just that I'm facing some errors and I'm debugging them.
> Can you just give me an extension of one more day, please?
> Thanks!

Sure 👍🏻

**Comment by RushanKhan1** [comment]
Hey @SpecTEviL, what's the status?

**Comment by SpecTEviL** [comment]
Hey, @RushanKhan1 and @AnanyaNegi sorry for the inconvinience. I've been facing some errors hence wasn't able to make the progress. Although once I sort them out you can reassign me so that I can make the PR. I'll ping you once it works fine.
Thanks!

**Comment by arbazalam01** [comment]
can i work on this issue as a part of GSSOC'21

**Comment by RushanKhan1** [comment]
@SpecTEviL No problem, but now the issue has to be assigned to someone else as per the rules.

@arbazalam01 Sure the issue is yours to work with, you have 4 days to complete it. All the best!

**Comment by Ayush0730** [comment]
Can I work on this issue?

**Comment by AnanyaNegi** [comment]
> 
> 
> Can I work on this issue?

Sure. It has been assigned to you. You can start working on it.
