### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by shrishti-c** [ALPHAVIO/BlogSite#288]
While starting project, these bugs are encountered
![Screenshot_125](https://user-images.githubusercontent.com/73748606/110812752-e3ef5c80-82ad-11eb-9897-3fcfa334a396.png)

**Comment by prajjwalarora** [comment]
this is not a bug actually you forgot to add the .env file with relevant environment variables.

**Comment by Pranav016** [comment]
> this is not a bug actually you forgot to add the .env file with relevant environment variables. one of them is for connecting with db that causing a mongoose error.

@prajjwalarora Thanks for helping her, I like your open-source spirit!

@shrishti-c If you are still having issues, do add a couple more screenshots so that I can review. The whole error message is still not visible.

**Comment by aniketlodh** [comment]
This is not an error as said by @prajjwalarora. Besides adding environment variables, you need to start MongoDB in a new cmd tab.
