### ISSUE TITLE
To change the color and style of Navbar and make it adjustable according to different devices

### ISSUE THREAD

**Issue by gritika18** [ALPHAVIO/BlogSite#289]
The  color of the navigation bar is similar to the color of the page. It is getting mixed with the main content.                                      I would like to change the color of navigation bar and also the positions of the navbar contents. I would also love to make it look good according to different devices.
This will be beneficial for the users if they are opening the website on a different device. The navbar will get adjusted according to the device.

**Comment by RushanKhan1** [comment]
Hi @gritika18!
The website color scheme is already being worked upon under issue #268 and our current navbar is fully responsive, however, if you want to make further improvements then please create a different issue focusing on those improvements. So for now please find a different issue to work with or create a new one after making sure a similar issue doesn't exist.

**Comment by gritika18** [comment]
Ok thankyou I'll look for other issues.
