### ISSUE TITLE
Some color and ui related issue.

### ISSUE THREAD

**Issue by Abhinaba006** [ALPHAVIO/BlogSite#291]
### Feature request-
The current color of the website is unattractive due to high contrast in the dark mode.

### Describe the solution you'd like
I will like to edit the partial and css file to make the color theme more attractive that will ultimately make the website more decorated.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Abhinaba006** [comment]
sir if there is a design you will like to implement I can do that, If so, can you please send me the design or otherwise I will do it by myself, You can mail me at abhinaba006@gmail.com.

**Comment by RushanKhan1** [comment]
Hey @Abhinaba006, thanks for your interest in the project!
The whole color scheme of the website is already being worked upon under issue #268 therefore please find a different issue to work with or create a new one after making sure that a duplicate doesn't exist.

**Comment by Abhinaba006** [comment]
Ok, I will check before creating a new issue
