### ISSUE TITLE
issue regarding color code and navbar and content of the main page

### ISSUE THREAD

**Issue by oneknucklehead** [ALPHAVIO/BlogSite#292]
**Describe the bug**
The color code of the website looks quite bleak and the navbar and the main content of the webpage also look quite squeezed.
Describe the solution you'd like:
I would like to change the color code of the website so as to make the website look more attractive by adding some changes to the CSS and also change the look of the main page and the navbar which looks quite squeezed.

**Comment by RushanKhan1** [comment]
Hey @oneknucklehead! Thanks for your interest in the project.
This issue is very similar to issue #268.
Please create a new issue or find a different issue to work with and before creating a new issue please check if a similar issue already exists.

**Comment by oneknucklehead** [comment]
Hey @RushanKhan1! Thank you for pointing it out, I might have not seen the issue earlier. I wanted to know that whether I can still work on this issue or not?

**Comment by RushanKhan1** [comment]
Well, @FireQueen-3010 is already working on the issue, so if you still want to work on it then you can wait for her to make her pull request and then improve upon that, or if she doesn't make one within the allotted time then you can ``/assign`` yourself the issue.
