### ISSUE TITLE
Google Oauth while signing up

### ISSUE THREAD

**Issue by udaymittal7** [ALPHAVIO/BlogSite#293]
### Feature request-
I want to add the Google Oauth in the signup page for the ease for users. I will be using passport and passport google strategies for building this.

### Describe alternatives you've considered
We can also make facebook and twiitter authentication but google seems to be the most appropriate.

### Describe how this feature will be useful to our readers.
It will ease up the sign in process.

I want to work on this as a participant of GSSOC'21.

**Comment by RushanKhan1** [comment]
Hey @udaymittal7!
Third-party authentication is already being worked upon under issue #269, therefore please create a new issue or find a different issue to work with and before creating a new issue please check if a similar issue already exists.
