### ISSUE TITLE
Alignment issue on home page.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#295]
### **Describe the bug**
![image](https://user-images.githubusercontent.com/54665036/110846811-39d5fb80-82d2-11eb-8dd8-900f1ce8a3b6.png)

### **To Reproduce**
1. Go to home page of the website

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by hrushikesh-git** [comment]
Hey @Pranav016 I would like to work on this issue please assign it to me, GSSOC'21 participant

**Comment by RushanKhan1** [comment]
The issue has been fixed hence closing it.
