### ISSUE TITLE
Improve Navbar

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#296]
### Feature request-
Change color of navbar and update headline

### Describe the solution you'd like
A new color scheme for the navbar and update the heading 'Daily journal' to something different. You can be creative.
![image](https://user-images.githubusercontent.com/54665036/110847133-8d484980-82d2-11eb-9005-81fece1c946a.png)

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by hrushikesh-git** [comment]
@Pranav016 I would like to work on this issue. I am a GSSOC'21 participant

**Comment by shudhanshu03** [comment]
@hrushikesh-git  , Just comment "/assign" and start working on it .

**Comment by hrushikesh-git** [comment]
> @hrushikesh-git , Just comment "/assign" and start working on it . You will automatically assigned for this issue .

Thanks man

**Comment by shudhanshu03** [comment]
/level2/

**Comment by shudhanshu03** [comment]
@hrushikesh-git  You have 4 days to complete this thing as this is lvl2 task so @Pranav016 and team has decided to give 4 days and its enough for this issue . Keep up the good contribution .

**Comment by hrushikesh-git** [comment]
Okay Great alredy started working

**Comment by Shraddha13Jain** [comment]
/assign
Hey!! @shudhanshu03  , I am a participant of GSSoC'21. I would take up this issue.
Can you please assign me this issue.

**Comment by Ananya-Sharma** [comment]
/assign 
As participant of gssoc I would like to work on this issue, please assign it to me.

**Comment by GurshehzadSingh** [comment]
/assign 
I'm a participant of GSSOC and I want to work on this issue.

**Comment by RushanKhan1** [comment]
@hrushikesh-git It has been 9 days, Are you still working on this issue?

**Comment by GurshehzadSingh** [comment]
No.. Because someone else also commented assigned.. So I didn't work on it
as I thought the issue was assigned to someone who commented before me.

**Comment by hrushikesh-git** [comment]
> @hrushikesh-git It has been 9 days, are you still working on this issue?

yes I am working with this issue and I am in touch with @Pranav016  last time was PR was cancelled do some major code changes, hence it took time

**Comment by Pranav016** [comment]
raise new issue for changes required, since a lot of changes have happened since this issue was raised..
