### ISSUE TITLE
Issue in opening blog posts || Bug

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#298]
### **Describe the bug**
Error on trying to open blog posts after merging #290 

### **To Reproduce**
1. Go to home page
2. Click on READ MORE on any posts

### **Expected behavior**
Should open the blog posts.

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Abhinaba006** [comment]
It must be route related something, I am working on it
