### ISSUE TITLE
Add contribution Guidelines for new contributors.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#3]
# About issue-
Add a file `CONTRIBUTING.md` which includes all the contribution guidelines and the best practices such as making a new branch to contribute, for all the beginners.
[Reference file](https://github.com/Pranav016/ToDoista/blob/contributing/CONTRIBUTING.md)

**Comment by tanvimoharir** [comment]
@Pranav016 Let me know if I can take this up and you can assign it to me. As mentioned in #16 I'm new to open source contributions and any help/suggestion or otherwise are more than welcome. Thanks.

**Comment by Pranav016** [comment]
Thank you for your interest @tanvimoharir , I'll be more than happy to help you get started with open source. I am glad to tell you that this repository has been accepted for an open-source program that is going to begin in a week. Till then we might not be accepting any new pull request on this project. Refer to #21 

Sorry for the inconvenience. There are a lot of other repositories available in this organization where you can raise issues and I'll be there to guide you throughout your contribution.
Happy Learning!

**Comment by luckykumarirai** [comment]
I would like to contribute to this issue.

**Comment by Pranav016** [comment]
> I would like to contribute to this issue.

Sure, issues will start getting assigned from 21st Jan onwards. Till then get familiar with the project base and continue to experiment with it🙂

**Comment by Pranav016** [comment]
@luckykumarirai I have assigned this to you, use the reference file that I have given above. I want this issue to be worked upon first because a `CONTRIBUTING` file is very important for a project.

**Comment by luckykumarirai** [comment]
Hello @Pranav016  
I have sent the PR with contributing.md file please review it.

**Comment by Pranav016** [comment]
Closed via #35
