### ISSUE TITLE
MongoError warning at starting of the server

### ISSUE THREAD

**Issue by Abhinaba006** [ALPHAVIO/BlogSite#300]
### **Describe the bug**
When the server is started, in the console it shows a mongoerror warning

### **To Reproduce**
1. Go to console
2. run 'npm run dev'

### **Expected behavior**
It should not show the warning.

### **Screenshots**
![image](https://user-images.githubusercontent.com/54203624/110890451-a24cc900-8322-11eb-8c08-91f7ee3bc459.png)

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by srk224** [comment]
I have solved the issue
Now it looks like this
![2021-03-12](https://user-images.githubusercontent.com/63584405/110905846-26a64880-8331-11eb-81d9-dd482639e87a.png)
Should I create my PR??

**Comment by srk224** [comment]
Can you please add the gssoc label and tell me if I should create my PR as the issue has been solved!

**Comment by Abhinaba006** [comment]
Great work @srk224! You can make the pr if you want, mentors can add the level label.
How did you solve the problem?

**Comment by srk224** [comment]
We just needed an extra line of mongoose set statements and we needed to update the mongoose version..
Thats all and the warning was removed
I aam creating a PR. Please add the gssoc label
Thanks a lot

**Comment by srk224** [comment]
I have created the PR. Thanks alot.Looking forward for more issues

**Comment by AnanyaNegi** [comment]
/gssoc/

**Comment by AnanyaNegi** [comment]
/level2/

**Comment by srk224** [comment]
Their is some after creating the PR. Can you please tell me 
what is the error and how should I solve it??
P.S-Check my PR

**Comment by AnanyaNegi** [comment]
> 
> 
> Their is some after creating the PR. Can you please tell me
> what is the error and how should I solve it??
> P.S-Check my PR

I have reviewed your PR. You can check the changes required there.
