### ISSUE TITLE
Login button needed at the home page

### ISSUE THREAD

**Issue by Abhinaba006** [ALPHAVIO/BlogSite#301]
### Feature request-
On the home page, it only shows options of login or signs up when an unauthenticated user tries to create a post instead of that there must be a login/signup option.

### Is your feature request related to a problem? Please describe. (optional)
It is a feature and helpful for users as it is without a signup option it is hard for the user to know how to create an account.

### Describe the solution you'd like
I will like to add an icon for login on the home page that will guide a new user to create a new account or login for existing user.

### Additional context
![image](https://user-images.githubusercontent.com/54203624/110891703-22742e00-8325-11eb-8fd5-25c04b78e7c7.png)
The button will be on the top right corner in the navbar

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by AnanyaNegi** [comment]
/gssoc/

**Comment by AnanyaNegi** [comment]
/level2/
