### ISSUE TITLE
UI Issue - Footer icon links

### ISSUE THREAD

**Issue by tanishq-arya** [ALPHAVIO/BlogSite#306]
### **Describe the bug**
The icons in the footer don't work.

### **To Reproduce**
1. Go to "https://blogsite321.herokuapp.com/"
2. Click on any icon in the footer
3. You're still on home page

### **Expected behavior**
It should take you to the website profile for the same.

### **Additional context**
Add the links in href="" of <a> tags or remove them if not required.

**Comment by tanishq-arya** [comment]
I couldn't find any issue similar to this and I am not sure if the ui design one solves this, so I have not self-assigned myself this issue. If I can work on this, I would like to do so.

**Comment by ankitaugale23** [comment]
I would like to work on footer styling. for Example, Adding some effects to icons and adding some styling to text in the footer. If @tanishq-arya as he mentioned is working on functionality only. Can I take the designing part of the footer? @Pranav016 @AnanyaNegi @RushanKhan1 @shudhanshu03. 
If you are ok with me working on this. Should I create a different issue or can I directly work on this. 
Please let me know Thank you!

**Comment by tanishq-arya** [comment]
Hey @ankitaugale23 You can work on it if they say. The functionality part is a very small issue. If they assign you the issue to work on Add the links in href="" of tags or remove them if not required in the html file.

**Comment by tanishq-arya** [comment]
Styling part is I guess being handled in the issue #268

**Comment by RushanKhan1** [comment]
Hey @tanishq-arya! We appreciate your willingness to contribute!
The links in the footer are for aesthetic purposes only. Our app doesn't have any social media presence hence no profiles we can link to. The source for the links is ``#!`` which acts as a dummy link which means that it has been purposely kept that way. Therefore I request you to please find a new issue to work on or create a new one. Also, good job checking previous issues before creating new ones!

**Comment by RushanKhan1** [comment]
Hi @ankitaugale23!
@tanishq-arya is right, the style for the full website is currently being worked upon. What you can do is wait for the assigned person to send her pull request and check if the footer has been styled, if not, then create a new issue and start working on it.
