### ISSUE TITLE
Adding styling to Contact Us Page to make it look more lively

### ISSUE THREAD

**Issue by ankitaugale23** [ALPHAVIO/BlogSite#308]
### Feature request-
Contact us page of website looks very plain. I wanted to add some styling and effects to the Contact us page so it will look more lively.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
Adding styling to the paragraph written over there like other websites will look more appealing to visitors. Also instead of directly giving links I can add a favicon and will provide the mail link after hovering over them by using some effects.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by ankitaugale23** [comment]
Should I start working o this? @AnanyaNegi @Pranav016 @RushanKhan1 @shudhanshu03

**Comment by shudhanshu03** [comment]
> Should I start working o this? @AnanyaNegi @Pranav016 @RushanKhan1 @shudhanshu03

Go on , I have checked no one is working on similar issue . You are already assigned .

**Comment by shudhanshu03** [comment]
/gssoc/

**Comment by shudhanshu03** [comment]
/level2/

**Comment by ankitaugale23** [comment]
Sure thanks. I will make a PR in two days.

**Comment by ankitaugale23** [comment]
Would you mind telling me what I have done wrong? @shudhanshu03 @AnanyaNegi @Pranav016 @RushanKhan1

**Comment by ambivert-sam** [comment]
Hey @ankitaugale23  , I'm participant on GSSOC'21 I want to contribute on this issue will you please assign it to me?

**Comment by RushanKhan1** [comment]
@ankitaugale23 Did you pull the new changes and are you working on the updated code?

**Comment by Pranav016** [comment]
Contact us page already updated, reopen issue if you have more improvement suggestions.
