### ISSUE TITLE
Feature Image

### ISSUE THREAD

**Issue by hrushikesh-git** [ALPHAVIO/BlogSite#315]
As the Blog from the blog title, we get the idea of the content of the blog, but images give even more clear thoughts as they are visually pleasing and provide a direct idea of the blog. So we can add image or photo property to the database and create the routes for uploading an  image
![photo](https://user-images.githubusercontent.com/65762074/110986844-360aad80-8394-11eb-85b0-298fb2687c1f.png)
image and retrieving

**Comment by AnanyaNegi** [comment]
/gssoc/

**Comment by AnanyaNegi** [comment]
/level2/

**Comment by hrushikesh-git** [comment]
yes i am working on it my one PR is yet to merge
