### ISSUE TITLE
working with mongoose means working with promises

### ISSUE THREAD

**Issue by abhay27chauhan** [ALPHAVIO/BlogSite#320]
### Proposal

if you are working with mongoose, means you are working with promises. So, you need to handle promise. This is an easy fix but good for long term. 

I suggest instead of this:

- **mongoose.connect(URL, { useNewUrlParser: true, useUnifiedTopology: true });**

You should do this:

`
const connectDB = async () => {

    try{

            const conn = await mongoose.connect(URL, {useNewUrlParser: true, useUnifiedTopology: true});
            console.log(`MongoDB Connected: ${conn.connection.host}`)
    }catch(err){

            console.log(err)
            process.exit(1)
    }
}

connectDB();
`

It is good practice :)

**Comment by abhay27chauhan** [comment]
I am a participant of GSSOC21, so please let me know if this is a valid proposal

**Comment by Pranav016** [comment]
You want to convert these to asynchronous requests right ?

**Comment by abhay27chauhan** [comment]
Yes

**Comment by Athira2199** [comment]
yes I agree with @abhay27chauhan its throwing error when I am trying with mongodb atlas. Suggesting to change it based on @abhay27chauhan's solution.

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/
