### ISSUE TITLE
Password should be hashed by using Middleware in the model

### ISSUE THREAD

**Issue by Abhinaba006** [ALPHAVIO/BlogSite#324]
### **Describe the bug**
Currently the password is hashed whenever the new sign up router is called, instead of this we can hash the password before saving it in the model by using Middleware, it will be a more correct approach.

By using this method we can save the password from any router, not only from the sign up route and it will be hashed.

### **To Reproduce**
It is in the file
Routes/user.route.js

### **Expected behavior**
It should be in the model so we can save the password from other route and edit the password if needed.

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
* According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies,the decision of the maintainer will be final.
```
level0- 2 days
level1- 3 days
level2- 4 days
level3- 5 days
```

**Comment by Abhinaba006** [comment]
@AnanyaNegi ma'am, please add gssoc and level label, as a gssoc 21 participant it will be helpful for me.

**Comment by shudhanshu03** [comment]
/gssoc/

> @AnanyaNegi ma'am, please add gssoc and level label, as a gssoc 21 participant it will be helpful for me.

**Comment by shudhanshu03** [comment]
@Abhinaba006 Start Woking on it 👍.

**Comment by RushanKhan1** [comment]
Hey @Abhinaba006, are you still working on this issue?

**Comment by Abhinaba006** [comment]
The code was heavily changed and needed to be pulled, I have done it previously but can't send cause the code is changed and my code will cause conflict and added to this my 3rd sem is going on this week, I have analog and digital electronics exam tomorrow, so if you consider me two days more it will be done.

**Comment by Abhinaba006** [comment]
Pranav sir told us in discord that we can send pr from yesterday that is why I didn't send, it will not be accepted. Please allow me two more days
