### ISSUE TITLE
Categories and Tags.

### ISSUE THREAD

**Issue by Athira2199** [ALPHAVIO/BlogSite#325]
### Feature request-
Adding categories and tags for blog posts could increase the search ability and readability of the posts.

### Is your feature request related to a problem? Please describe. (optional)
No

### Describe the solution you'd like
The categories could be pre-defined or we could let the user create new categories on which they could work. Tags can be given by the user and we could give the autocomplete functionality for it based on existing tags in the db.

### Describe alternatives you've considered
Open to discussions.

### Describe how this feature will be useful to our readers.
Adding categories and tags for blog posts could increase the search ability and readability of the posts.

### Additional context
I am GSSoC21 participant. I would like to contribute in this feature if you feel the feature can be added. @Pranav016 @AnanyaNegi @RushanKhan1 @shudhanshu03 

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level0- 2 days
level1- 3 days
level2- 4 days
level3- 5 days
```

**Comment by RushanKhan1** [comment]
@Athira2199, It has been 4 days since you were assigned the issue, are you still working on it?

**Comment by Athira2199** [comment]
yes I am working on it, please provide me time till weekend. I am working on it @RushanKhan1
