### ISSUE TITLE
Able to delete comments of other users.

### ISSUE THREAD

**Issue by Athira2199** [ALPHAVIO/BlogSite#326]
### **Describe the bug**
User A is able to delete comments of user B which ideally should not be the case. Users should only be able to delete their own comments and not the comments of other users. 

### **To Reproduce**
1. Go to any blog which has a comment other than yours.
2. Delete the comment.
3. You will see that the comment gets automatically deleted.

### **Expected behavior**
Ideally the user who has entered the comment should only be able to delete his/her comment and only admins of the site should be given the right to delete comments of any user.

### **Screenshots**
None.

### **Additional context**
I am a GSSoC 21 participant. I would like to work on this bug. It would be great if you assign it to me. @Pranav016 @AnanyaNegi @RushanKhan1 @shudhanshu03 

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
* According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies,the decision of the maintainer will be final.
```
level0- 2 days
level1- 3 days
level2- 4 days
level3- 5 days
```

**Comment by aniketlodh** [comment]
Currently, the application is set in a way that anyone can delete anyone's comment. This is done with the sole purpose that no vulgar comment can be there in the comments.

**Comment by samad-yar-khan** [comment]
Hey , we can probably add a level of authorisation where a user should be able to delete the comments made on his in case it is inappropriate . I think it would be better than allowing everyone o delete everyones comments

**Comment by Athira2199** [comment]
To reduce inappropriate comments, allowing users to delete others comments won't be an appropriate action. Like if the author of the posts feels some one is giving negative feedback of his posts, then he might  delete the comments when actually the comment could be a genuine one. In order to check on inappropriate comments we could give a flag option in the comments.

**Comment by Pranav016** [comment]
I think flag feature issue covers this..
