### ISSUE TITLE
a refactoring suggestion.

### ISSUE THREAD

**Issue by Athira2199** [ALPHAVIO/BlogSite#327]
https://github.com/ALPHAVIO/BlogSite/blob/e5cc4227a36fb873799efbe79334b4f73049cb96/routes/user.router.js#L108
changing line number based on update

In the above section to check for if a particular username or password exists , we are performing two db operations when actually we could just create ine single db operation with **$or** of mongodb.

If you feel this could be a effective code refactoring please assign the issue to me. I am GSSOC21 participant. @AnanyaNegi @Pranav016 @RushanKhan1 @shudhanshu03

**Comment by RushanKhan1** [comment]
Hey @Athira2199, are you still working on it?

**Comment by Athira2199** [comment]
yes submitting the pull request tommorow @RushanKhan1
