### ISSUE TITLE
Improving the blog 

### ISSUE THREAD

**Issue by Athira2199** [ALPHAVIO/BlogSite#328]
https://github.com/ALPHAVIO/BlogSite/blob/2fb3464d4ae5f8796123aeb31630b5cb807982a9/routes/post.router.js#L23

I feel this as an inefficient approach to find the details of the blog. We could enhance this section to make mongodb itself perform the find the blog by title by using Blog.find({blogTitle : requestedTitle}). I am GSSoC21 participant. Please assign this issue to me. @Pranav016 @AnanyaNegi @RushanKhan1 @shudhanshu03

**Comment by Athira2199** [comment]
> https://github.com/ALPHAVIO/BlogSite/blob/2fb3464d4ae5f8796123aeb31630b5cb807982a9/routes/post.router.js#L23
> 
> I feel this as an inefficient approach to find the details of the blog. We could enhance this section to make mongodb itself perform the find the blog by title by using Blog.find({blogTitle : requestedTitle}). I am GSSoC21 participant. Please assign this issue to me. @Pranav016 @AnanyaNegi @RushanKhan1 @shudhanshu03

/assign

**Comment by prajjwalarora** [comment]
@Pranav016 @Athira2199 this issue will be fixed automatically as #287 is merged. because fetching the blog using this way is an inefficient method. using postId for this already extracting unique posts, instead of fetching all and comparing to find required one.

**Comment by Athira2199** [comment]
Ok got it just saw your code. I would like to suggest on having asyn/await. It makes the code cleaner.

**Comment by prajjwalarora** [comment]
@Athira2199 that can be done but required new issue because that also needed good error handling as well, like creating global error handler. because in this code no error handler is there. and separate error handling for each controller can create problems as code scale.

**Comment by Athira2199** [comment]
Ok I had actually implemented the try-catch block for this and did it. Shall I keep just try catch for this and once this new issue is opened we could change the try catch block, or should I remove the asyn-await functionality from my current pr. @prajjwalarora

**Comment by prajjwalarora** [comment]
@Athira2199 have to ask from members and admin.

**Comment by Pranav016** [comment]
I agree with @prajjwalarora, once the PR for the route issues gets merged, then raise a new issue to make the code cleaner and scalable by adding try catch and async await.
Closing for now, reopen if required
