### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by Athira2199** [ALPHAVIO/BlogSite#329]
### Feature request-
404 page is common to inform the user that the requested page or url does not exist. 

### Is your feature request related to a problem? Please describe. (optional)
Its not a problem but its rather an enhancement.

### Describe the solution you'd like
Usually when we don't have a 404 page , the browser sent a message like **Cannot GET /post** . This is usually represented as a minus point for sites. Hence I would suggest that we could create a 404 page for this.

### Describe how this feature will be useful to our readers.
It lets them know they have landed on a page or url which is not present. We could even redirect them to the home page.

### Additional context
I am a GSSoC21 participant and I would like to work on this feature enhancement. In case you feel this is a required feature and you feel we can add it to our site please assign this to me. @Pranav016 @AnanyaNegi @RushanKhan1 @shudhanshu03 .

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level0- 2 days
level1- 3 days
level2- 4 days
level3- 5 days
```

**Comment by RushanKhan1** [comment]
Hey @Athira2199, are you still working on this issue?

**Comment by Athira2199** [comment]
Hi yes I am working on it, will submit pull request by tommorow.

**Comment by ShambhaviSharma0110** [comment]
Hey if it still isn't done can I work on it?
