### ISSUE TITLE
Improving the footer

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [ALPHAVIO/BlogSite#330]
### Feature request-
**Changing the alignment of content, color theme and making the footer responsive.**

![original-footer](https://user-images.githubusercontent.com/66208607/111033235-2d6ab380-8436-11eb-8905-c82915c819c5.png)

I am GSSoC21 participant. Please assign this issue to me. @Pranav016 @AnanyaNegi @RushanKhan1 @shudhanshu03

**Comment by Athira2199** [comment]
@Bhavya-Sehgal how did you slash assign. I am not  able to assign like this in my issue ?

**Comment by RushanKhan1** [comment]
@Bhavya-Sehgal Hey, It's been 4 days since this issue has been assigned to you, are you still working on this issue?

**Comment by simranbhalla3** [comment]
Hey! Can i work on this issue? @RushanKhan1

**Comment by RushanKhan1** [comment]
@simranbhalla3 Okay, I am reassigning this issue to you since the original assignee hasn't updated their status. All the best!

**Comment by RushanKhan1** [comment]
@simranbhalla3 Hey, are you still working on this issue? What's the status?
