### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by A7abhilash** [ALPHAVIO/BlogSite#333]
### Feature request-
Improve the UI of post-preview using bootstrap to look it more neater with proper paddings and margins.

### Is your feature request related to a problem? Please describe. (optional)
Currently the UI is bit clumsy, so would like to make it more neater, clean and attractive.

### Describe the solution you'd like
Use bootstrap column concept and implement proper post-preview

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level0- 2 days
level1- 3 days
level2- 4 days
level3- 5 days
```

**Comment by A7abhilash** [comment]
@Pranav016 Can u please mention the assignee to me??

**Comment by AnanyaNegi** [comment]
Hi @A7abhilash . Great to see your initiative however this issue is already been assigned to someone else. See reference #268 . You may take a look at some other issues.
