### ISSUE TITLE
No need to use body-parser when using express version 4.16+

### ISSUE THREAD

**Issue by udaymittal7** [ALPHAVIO/BlogSite#344]
Express version 4.16+, their own body-parser implementation is now included in the default Express package so there is no need for you to download another dependency.

You have added a line to your code that looks like the following:

app.use(bodyParser.urlencoded({extended: true}));

You can replace that with:

app.use(express.urlencoded());

If you find it relevant, please assign me this and add the relevant tags. Thank you.

**Comment by Pranav016** [comment]
repeated #319
