### ISSUE TITLE
Frontend: change background and make color scheme better and attractive.

### ISSUE THREAD

**Issue by lakshita15** [ALPHAVIO/BlogSite#355]
I'm gssoc'21 participant would like to make all the colors in sync and make it colorful and impressive. 
I want to work on this issue
Can you assign issue to me ?
i'll submit before deadline.

**Comment by RushanKhan1** [comment]
@lakshita15 The pull request #358 has been merged recently and that worked on this exact same issue, so, please update your fork, give the updated website a look and then if you have any further improvements, create a new issue focusing on those exact improvements.
