### ISSUE TITLE
Make the code clean

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#360]
### Feature request-
There is too much code cluttered in the `app.js`. Divide it into its respective routes and folders and make the file and folder structure clean.

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by BullHoN** [comment]
@Pranav016 Can you please help me I am a bit confused. In the app.js file, all the API request corresponding to posts use postName as a parameter in the URL whereas there is an existing file post.router.js in the routes folder all the API request use postId as the parameter which one is correct ??

**Comment by Pranav016** [comment]
> @Pranav016 Can you please help me I am a bit confused. In the app.js file, all the API request corresponding to posts use postName as a parameter in the URL whereas there is an existing file post.router.js in the routes folder all the API request use postId as the parameter which one is correct ??

Post ID is correct, comment down the post name one and then try if post id works. Otherwise we'll have to fix it..

**Comment by BullHoN** [comment]
Ok I am trying 👍👍

**Comment by Pranav016** [comment]
Also I am also working on cleaning the code, My main target would be to get it back in working condition. Then for any additional folders or cleaning code you can do..
Works for you ?

**Comment by BullHoN** [comment]
Ok First you solve the issue then I will make it clean later

**Comment by BullHoN** [comment]
Maybe you may have seen it by now Blog is used twice in the app.js file so it needs to be updated in Blog.model.js in the models folder and removed from app.js

**Comment by BullHoN** [comment]
Hope that helps 😊😊

**Comment by Pranav016** [comment]
> Maybe you may have seen it by now Blog is used twice in the app.js file so it needs to be updated in Blog.model.js in the models folder and removed from app.js

Yes ☺️

**Comment by Pranav016** [comment]
My pull request was merged. 
Now you can start working. Some changes that I want you to do as a part of this level 3 issue -

* Add folder structure to assets folder, that would require all the paths where these images have been used to be updated.
* Add comments in the code to divide into sections. Most of the routers, app middlewares etc have already been commented. The .EJS files in views folder have no comments, I want you to add comments and divide it into sections.
* Indent and format the code properly in .EJS files / all files in views folder. I have formatted the code in all the other files using prettier but prettier does not format .EJS files therefore they need to be done.
* Add comments in styles.css to divide into sections like ` style for navigation bar` etc.
* Organize the public folder. Might require change of paths in files where it is used. (Optional point)
* If a user is authenticated, he / she is able to go back to login and signup page which shouldn't be there. Work on it and any logged in user shouldn't be able to access them unless they logout.

**Comment by Pranav016** [comment]
Can you do this ^ ? @BullHoN

**Comment by BullHoN** [comment]
@Pranav016  Yes, I can try

**Comment by Pranav016** [comment]
> @Pranav016 Yes, I can try

Can a PR to solve this issue could be made by today ? Coz after this we are going to start accepting PRs therefore I want to get this merged asap. I might also have to test the PR so it might take time

**Comment by Pranav016** [comment]
@BullHoN any updates ?

**Comment by BullHoN** [comment]
@Pranav016 I am really sorry 😔😔  I didn't check the comments can I do it tomorrow morning ??

**Comment by Pranav016** [comment]
> @Pranav016 I am really sorry 😔😔 I didn't check the comments can I do it tomorrow morning ??

Ok, I hope to see your PR first in the morning :)

**Comment by BullHoN** [comment]
@Pranav016 I had made some changes
- formatted and added comments in .ejs files
- added comments in styles.css
- restrict access to sign-up and login routes when logged in
- search bar was not working there was a small issue resolved it

routes folder is currently placed in the public folder should I change its path ??, I didn't get your first point regarding assets one can you please explain a bit.

**Comment by Pranav016** [comment]
> @Pranav016 I had made some changes
> 
> * formatted and added comments in .ejs files
> * added comments in styles.css
> * restrict access to sign-up and login routes when logged in
> * search bar was not working there was a small issue resolved it
> 
> routes folder is currently placed in the public folder should I change its path ??, I didn't get your first point regarding assets one can you please explain a bit.

Good work, assets can be ignored for now. It's not that important. Routes folder placed in pubic ? I don't get it, it's there in the root directory, not in public folder.

So PR looks good, I'll test it once then merge

**Comment by BullHoN** [comment]
@Pranav016 sorry about routes I was a bit sleepy 😴😴 😅😅

**Comment by Pranav016** [comment]
> @Pranav016 sorry about routes I was a bit sleepy 😴😴 😅😅

No worries, good work
