### ISSUE TITLE
About Us page

### ISSUE THREAD

**Issue by Mitali-laroia** [ALPHAVIO/BlogSite#373]
### Feature request-
Currently the font colour and background colour of the about page is kind of merging and making it difficult to distinguish between text and page.

### the solution I'd like to implement
First of all change in colour shade,font and texture. Adding proper alignment with div and a further requests is to provide some images inorder to add a carousel to make it more interactive.

###  how this feature will be useful to our readers.
Having right alignment and colour shades always increases the user interactivity and helps to make a impact in the subconscious mind of the user to make them visit the web page again.

<hr/>

```
level - 1: 3 days
Working under GGSOC'21
```

**Comment by simranbhalla3** [comment]
Hii Can I work on this issue? I am a gssoc participant , would like to work on this issue

**Comment by Pranav016** [comment]
Is this issue still relevant ? Asking because the theme of the website was changed.
If yes, can you add a screenshot highlighting the issue you feel there is 🙂
