### ISSUE TITLE
Update gif in readme

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#378]
### Feature request-
Update the gif in README.md

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by innovation-platform** [comment]
I would like to work on this under GSSoC'21.

**Comment by innovation-platform** [comment]
I am facing an issue while signing up. Although my password satisfies all the requirements.
![image](https://user-images.githubusercontent.com/65439306/111732823-6bcffa80-889c-11eb-87f6-e7b407264f60.png)

**Comment by innovation-platform** [comment]
If you could give me existing credentials I will login and make the GIF. Or else shall I skip the compose part and make the GIF.

**Comment by Pranav016** [comment]
> I am facing an issue while signing up. Although my password satisfies all the requirements.
> ![image](https://user-images.githubusercontent.com/65439306/111732823-6bcffa80-889c-11eb-87f6-e7b407264f60.png)

Let me check

**Comment by innovation-platform** [comment]
ok. Thank You

**Comment by Pranav016** [comment]
* Sign-up is working fine for me, just use a longer password.
* compose can't be skipped since it is the main feature.
* Also show to dark mode feature in the gif

**Comment by innovation-platform** [comment]
ok. I will try it. Thank You.

**Comment by innovation-platform** [comment]
I have used the longest password possible. But I am still getting the same message. Please suggest me a password that worked for you.
![image](https://user-images.githubusercontent.com/65439306/111735831-ac327700-88a2-11eb-9b58-301605faf5cd.png)

**Comment by Pranav016** [comment]
> I have used the longest password possible. But I am still getting the same message. Please suggest me a password that worked for you.
> ![image](https://user-images.githubusercontent.com/65439306/111735831-ac327700-88a2-11eb-9b58-301605faf5cd.png)

my password was  Alphavio123

**Comment by innovation-platform** [comment]
Thank You. It worked now.
