### ISSUE TITLE
Different font syles should be available

### ISSUE THREAD

**Issue by tanya070820** [ALPHAVIO/BlogSite#382]
### Feature request-
I want to add two or more font styles.

### Is your feature request related to a problem? Please describe. (optional)
 Yes its related to the problem as by this the blog can be represented  in a effective way. 

### Describe the solution you'd like
I wiil use HTML and CSS.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
@tanya070820 Can you fill all the details about the issue ?

**Comment by naqeeb2710** [comment]
can i work on this issue??

**Comment by romasinha** [comment]
can I work on this issue?

**Comment by tanya070820** [comment]
Please  assign this issue to me @Pranav016

**Comment by Pranav016** [comment]
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.

**Comment by RushanKhan1** [comment]
Hey @tanya070820, are you still working on this issue?

**Comment by AnanyaNegi** [comment]
@tanya070820 if you are still willing to work on this issue, do respond here. Otherwise we have to assign it to the next person.

**Comment by tanya070820** [comment]
@AnanyaNegi yes I am working on it

**Comment by tanya070820** [comment]
@Pranav016 Sir can you please tell me which is the root file where I will edit.

**Comment by tanya070820** [comment]
@AnanyaNegi Ma'am please tell me the name of root file where I have to edit.

**Comment by AnanyaNegi** [comment]
> 
> 
> @AnanyaNegi Ma'am please tell me the name of root file where I have to edit.

you will need to create new folders in `assets` and add custom fonts in that. You can further search this issue online.

**Comment by tanya070820** [comment]
@AnanyaNegi Ma'am I have made changes but they are not showing it on the web site can you please tell me where I have to link it .

**Comment by AnanyaNegi** [comment]
> 
> 
> @AnanyaNegi Ma'am I have made changes but they are not showing it on the web site can you please tell me where I have to link it .

Did the changes show on the local port? If its visible on the local,you can create a pr then.

**Comment by Ayush0730** [comment]
If no one is working on this issue then can I be assigned for this?
