### ISSUE TITLE
create a logo for the website to make it look a little more attractive

### ISSUE THREAD

**Issue by aanchalrakheja** [ALPHAVIO/BlogSite#385]
Images never fail to attract audience and I think this blog site can be given an enhanced representation by a logo.
I would love to work on this.

**Comment by Pranav016** [comment]
Thank you for raising the issue, I am glad you want to contribute but we already have a logo. It is present in the assets folder if you want to check it out, one thing that I can recommend is we can add the logo in the navbar to the left of daily journal heading. You can raise an issue for that and work on it if you wish..
