### ISSUE TITLE
adding the logo in the left of navbar.

### ISSUE THREAD

**Issue by aanchalrakheja** [ALPHAVIO/BlogSite#386]
i would like to work on this issue.

**Comment by Pranav016** [comment]
/gssoc/

**Comment by aanchalrakheja** [comment]
Hey! I had a doubt. Can u please help me out with finding the file for the code. I could not configure the structure of the code like where do I find the code to add the icon.

**Comment by Pranav016** [comment]
> Hey! I had a doubt. Can u please help me out with finding the file for the code. I could not configure the structure of the code like where do I find the code to add the icon.

Check assets folder for the logo, there might be 3. Choose the best one. You can access the babbar in views/partials folder

**Comment by aanchalrakheja** [comment]
ok and I need to perform the entire setup before performing any changes? or will i be able to view the changes without node and mongodb installation?

**Comment by Pranav016** [comment]
> ok and I need to perform the entire setup before performing any changes? or will i be able to view the changes without node and mongodb installation?

You can view without mongodb..

**Comment by AnanyaNegi** [comment]
/level2/

**Comment by aanchalrakheja** [comment]
Is this okay?
![image](https://user-images.githubusercontent.com/68388581/113169859-a144f280-9263-11eb-9f23-d1984859f33c.png)
![image](https://user-images.githubusercontent.com/68388581/113169973-bf125780-9263-11eb-8931-cc4ca6d76ab1.png)

**Comment by Pranav016** [comment]
can the text be left aligned with the logo in mobile view ?
Also I can't find your PR, reopen PR or make a new one..

**Comment by aanchalrakheja** [comment]
I have opened a new PR for the same. Can u please guide me a bit about left aligning the text. I tried doing it but wasn't happening.
