### ISSUE TITLE
Add functionality to create comments in each post

### ISSUE THREAD

**Issue by sahilsaha7773** [ALPHAVIO/BlogSite#39]
I want to work on this as a part of JWOC.

**Comment by mak-ux** [comment]
Can I work on this issue??

**Comment by sahilsaha7773** [comment]
> Can I work on this issue??

Sorry, I am working on this

**Comment by Pranav016** [comment]
I have added a medium tag right now, I'll change the tag (medium or hard) according to the complexity of the code when I review it :)

**Comment by sahilsaha7773** [comment]
> I have added a medium tag right now, I'll change the tag (medium or hard) according to the complexity of the code when I review it

okay, sure, thanks!
