### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#4]
# About issue-
- Add screenshots of the website to the README.
- Add some GitHub tags and badges to beautify the README.
- Add a section right above maintainer section, for the Open Source events this Project was a part of. Add first entry as JGEC Winter of Code with a short description and logo of JGEC.
- Also add Mexili winter of Code for the Open Source events this Project was a part of. Add mexili logo and short description. Get info from their website.
- The website has been deployed via heroku and the environment setup is for local use, update the README accordingly.

**Comment by karunkarthik-git** [comment]
I'd like to contribute to it as a mentee of Jwoc.

**Comment by Aayush-hub** [comment]
@Pranav016 Can I work on this issue?

**Comment by Pranav016** [comment]
Can you discuss what changes are you going to make, what ideas you have. And also under which program will you be contributing.

**Comment by Aayush-hub** [comment]
@Pranav016  I am working under Mwoc

**Comment by Pranav016** [comment]
> @Pranav016 I am working under Mwoc. I will make all the changes requested in issue description.

Do one thing, instead of screenshots add a demo gif of the website to the README.
Just take a screen recording of the features of the website, how you publish posts and using the dark mode etc. Convert to gif and add it to the readme. Let me know if any help needed
