### ISSUE TITLE
Use email for log-in instead of username

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#405]
### Feature request-
Use email of user for logging in instead of username.
![image](https://user-images.githubusercontent.com/54665036/111908840-ccb82800-8a80-11eb-8e01-2133b072c76f.png)

### Describe how this feature will be useful to our readers.
People usually don't remember usernames of individual platforms but do remember their emails thus logging in using email is more convenient. 

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
Got a request from someone that their issue is dependent on this one so got the request to ask you to please complete it fast..

**Comment by SriSarveshA1** [comment]
@Pranav016  can i solve this issue?
