### ISSUE TITLE
Alignment of buttons

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/BlogSite#407]
The alignment of buttons seems to be messed up a little and  ```Number of posts:``` seems bit small and unclear, would like to improve upon these under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/111915617-35ad9900-8a9d-11eb-9e63-1d8d572b3889.png)

**Comment by satcasm** [comment]
@RushanKhan1 should I work on it or it isn't neccassary?

**Comment by RushanKhan1** [comment]
> @RushanKhan1 should I work on it or it isn't neccassary?

Yes @satcasm, you can work on it.
