### ISSUE TITLE
Alignment of Search bar

### ISSUE THREAD

**Issue by Smriti129** [ALPHAVIO/BlogSite#409]
<img width="475" alt="gssoc" src="https://user-images.githubusercontent.com/76429418/111974041-2114e380-8b25-11eb-995f-22aeff7dd951.PNG">
The alignment of search bar and the buttons looks bit disturbed. I want to adjust it according to the page and made it look lively.
I would like to work on this issue. Please assign it.

**Comment by Smriti129** [comment]
Should I start working on it? @RushanKhan1

**Comment by RushanKhan1** [comment]
> Should I start working on it? @RushanKhan1

Yes please go ahead.

**Comment by Smriti129** [comment]
Okay, Thank You. Can I know how many days do I have for the submission?

**Comment by RushanKhan1** [comment]
> Okay, Thank You. Can I know how many days do I have for the submission? @RushanKhan1

This looks like a level 2 issue so you have 4 days to complete it.

**Comment by AnanyaNegi** [comment]
Hey, @Smriti129 are you still working on this issue?

**Comment by Pranav016** [comment]
This issue is no more there on the website @AnanyaNegi @RushanKhan1
