### ISSUE TITLE
Adding flags for comments

### ISSUE THREAD

**Issue by Athira2199** [ALPHAVIO/BlogSite#411]
### Feature request-
Adding flag feature to restrict vulgar comments.

### Is your feature request related to a problem? Please describe. (optional)
When we have changed the comment delete permission as only author of the comment is allowed to delete his/her comments, there raised an issue regarding handling inappropriate comments.

### Describe the solution you'd like
An effective method would be allowing users to flag inappropriate comments.

### Describe alternatives you've considered
Another alternative is having an admin panel to moderate comments.

### Describe how this feature will be useful to our readers.
This  feature will give users to voice out their opinions regarding a post as well as maintain the integrity of the platform.

### Additional context
I would like to take up this task as part of GSSOC21
<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
If no one is working on this issue. May I get assigned for this?

**Comment by AnanyaNegi** [comment]
> 
> 
> If no one is working on this issue. Can I get assigned for this?

@Ayush0730 this issue has been assigned to you. You can start working on it.
