### ISSUE TITLE
Changing the format of date

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/BlogSite#412]
### Feature request-
The date shown in "posted on" section of the post and date shown on comment is in normal javascript format. It can be changed to a more human understandable format

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
I would like to format the date in a better manner, using moment.js 

### Describe alternatives you've considered
We can do this task using moment or dayjs library

### Describe how this feature will be useful to our readers.
It will help to see dates more clearly

### Additional context
Image of current post and comment page
![image](https://user-images.githubusercontent.com/68139755/112029634-78d04080-8b5f-11eb-9e01-6368ee58e870.png)
![image](https://user-images.githubusercontent.com/68139755/112029819-a3ba9480-8b5f-11eb-9a23-07ae74c6b33d.png)

Image after changing the format
![image](https://user-images.githubusercontent.com/68139755/112029914-b9c85500-8b5f-11eb-98c5-69d9cb4e462c.png)
![image](https://user-images.githubusercontent.com/68139755/112029955-c482ea00-8b5f-11eb-9434-f2420be48e9c.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
I am working under GSSoC'21

**Comment by RushanKhan1** [comment]
> Hi maintainers, I would like to know should I use dayjs or moment is OK. I have completed the task using moment, should I create a pull request or use dayjs instead

Hey @Ayush0730, I think it's completely your choice to use whatever package you want. Although, If you have time to kill then I would suggest redoing it in DayJs since it is much smaller than moment, also the API is pretty similar I think so it shouldn't be a problem.

**Comment by Ayush0730** [comment]
> > Hi maintainers, I would like to know should I use dayjs or moment is OK. I have completed the task using moment, should I create a pull request or use dayjs instead
> 
> Hey @Ayush0730, I think it's completely your choice to use whatever package you want. Although, If you have time to kill then I would suggest redoing it in DayJs since it is much smaller than moment, also the API is pretty similar I think so it shouldn't be a problem.

Should I close this issue? Since PR related to this issue has been merged

**Comment by RushanKhan1** [comment]
> > > Hi maintainers, I would like to know should I use dayjs or moment is OK. I have completed the task using moment, should I create a pull request or use dayjs instead
> > 
> > 
> > Hey @Ayush0730, I think it's completely your choice to use whatever package you want. Although, If you have time to kill then I would suggest redoing it in DayJs since it is much smaller than moment, also the API is pretty similar I think so it shouldn't be a problem.
> 
> Should I close this issue? Since PR related to this issue has been merged

Yes, you can close this issue. If you want to rewrite that part using DayJs then you can create a separate issue.
