### ISSUE TITLE
Allow only logged in users to Read individual blogs

### ISSUE THREAD

**Issue by Rimpi246** [ALPHAVIO/BlogSite#413]
### **Describe the bug**
Right now everyone landing on the home page can read individual blogs clicking on "Read More" button.

### **To Reproduce**
1. Go to Home page and compose a blog if none present
2. Log out and again go to home page
3. Click on Read More button in the blog
4. You will see you can read the whole blog.

### **Expected behavior**
Only logged users should be able to read your complete blogs.

### **Screenshots**
None

### **Additional context**
I would like to work on this issue as a part of GSSOC'21.Please `/assign` this to me.

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
@Rimpi246 comment here in the chat to get it assigned

**Comment by Rimpi246** [comment]
In discord?

**Comment by Rimpi246** [comment]
Please `/assign` this to me as a part of GSSOC'21

**Comment by Pranav016** [comment]
> Please `/assign` this to me as a part of GSSOC'21
Comment it /assign that would assign, right now I'll do it manually.

**Comment by Rimpi246** [comment]
The issue is solved. I'll be sending a pr soon

**Comment by Rimpi246** [comment]
Hello, I have sent a pr solving this issue with  #244  .Please review that
