### ISSUE TITLE
Show number of comments on the post

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/BlogSite#415]
### Feature request-
The number of comments should also be shown near read more button on the post

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
Add number of comments near read more button

### Describe how this feature will be useful to our readers.
This will give the reader an idea about how many users have commented on the post even before reading whole post

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
I am working under GSSoC'21

**Comment by nishihere19** [comment]
Hi, can I work on this issue under gssoc'21? Please assign it to me.

**Comment by Ayush0730** [comment]
> Hi, can I work on this issue under gssoc'21? Please assign it to me.

You can start working on the issue. If you want to get it assigned to you, just comment "/ assign" (without space and quotes)

**Comment by nishihere19** [comment]
Hi, I was setting up the project in my machine. While signing up, I am running into this error. Can anyone please guide me?
![Screenshot from 2021-03-23 22-37-59](https://user-images.githubusercontent.com/63252119/112188140-c1076580-8c28-11eb-9c5b-4d726b324431.png)

Thank You.

**Comment by Ayush0730** [comment]
> Hi, I was setting up the project in my machine. While signing up, I am running into this error. Can anyone please guide me?
> ![Screenshot from 2021-03-23 22-37-59](https://user-images.githubusercontent.com/63252119/112188140-c1076580-8c28-11eb-9c5b-4d726b324431.png)
> 
> Thank You.

Have you set environment variables in a .env file??

**Comment by nishihere19** [comment]
There was a typo in my .env, thanks a lot for the guidance.
