### ISSUE TITLE
Contact Us formatting

### ISSUE THREAD

**Issue by Vaibhav-afk** [ALPHAVIO/BlogSite#420]
### **What's the issue with `Contact Us` page?**
Actually there is nothing bigger but the format is quite unprofessional (**i.e** Subject field is above Email).

![1](https://user-images.githubusercontent.com/67143938/112112563-b1156480-8bdb-11eb-9231-28cd3a5d2467.PNG)

### **Expected**
Subject field should be below email followed by message.

**Comment by Vaibhav-afk** [comment]
I can fix it, please assign me.

**Comment by Aayu231** [comment]
/assign 

Hi, I would like to work on this issue. I'm working under G'SoC 2021!

**Comment by Vaibhav-afk** [comment]
@Aayu231 are you still working?

**Comment by Aayu231** [comment]
yes I'm working

**Comment by Vaibhav-afk** [comment]
Okay then
