### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by osamamagdy** [ALPHAVIO/BlogSite#432]
I am a GSSoC 2021 participant and I would like to work on this issue.

### Feature request-
Adding email verification to the website during sign-up

### **Describe the problem**
Users can insert any Random email while signing up for an account not just if it's not their email, but also it can be not an email at all

### **To Reproduce**
1. Go to the login page
2. Click on signup
3. Enter any random email you can think of unless it is previously stored
4. Congratulations! you're logged in to the system and you have a fictional email stored in the database

### Describe the solution you'd like
Sending email verification link to the entered email, if the user clicks on it then this email is approved to be a valid email.

### Describe alternatives you've considered
Maybe we can send a code to the email and ask the user to enter it after that.

Both solutions can be sent multiple times with a time gap between them.

### Describe how this feature will be useful to our readers.
It makes users sure that people on this Blog are real persons not the same person with different emails. Of course, they can make fictional emails and submit them but it's out of our hands in that case.

### **Additional context**
This is extremely dangerous in terms of security as users can impersonate people in real-life if they're using other people's emails.
Also, it is very harmful on the website as it could be spammed by more than an email and costing in terms of database.

<hr/>

**Note:**
* Do mention if you are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto-assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by osamamagdy** [comment]
I just need to know the level of this feature to schedule a timeline for it. @AnanyaNegi @Pranav016 @RushanKhan1

**Comment by Pranav016** [comment]
/level2/

**Comment by krishna-y2000** [comment]
@osamamagdy  hii , please ping me at ```kyadav #6342``` at discord when you start this work . I am also working on the same issue on another project.

**Comment by osamamagdy** [comment]
@Pranav016 I am almost done with this (sorry for latency ^_^) 
But I don't know which email of the organization should be used to send verification emails to users

**Comment by osamamagdy** [comment]
@Pranav016 @krishna-y2000 @AnanyaNegi @RushanKhan1 I implemented the code to use the email as environment variables
and raised a pull request #601
