### ISSUE TITLE
Alignment of Navbar in mobile mode

### ISSUE THREAD

**Issue by kotwani2883** [ALPHAVIO/BlogSite#433]
### Feature request-
The alignment of navbar elements is not responsive

Below attached is the SS of the same

![WhatsApp Image 2021-03-24 at 15 49 17](https://user-images.githubusercontent.com/56580582/112295256-bd6fef00-8cb9-11eb-95dc-fb02c57423f0.jpeg)

### Describe the solution you'd like
I would like to make the navbar responsive 

A would like to improve this under GSSOC '21.Kindly assign this to me as a part of the prementioned program.
Thanks!

**Comment by kotwani2883** [comment]
@RushanKhan1 Kindly let me know that the navbar in both the modes is same?
Can I change the complete navbar because neither its responsive nor it is properly assigned with too much code of CSS because using bootstrap we could reduce to a very large extent.

**Comment by RushanKhan1** [comment]
> @RushanKhan1 Kindly let me know that the navbar in both the modes is same?
> Can I change the complete navbar because neither its responsive nor it is properly aligned with too much code of CSS because using bootstrap we could reduce it to a very large extent.

Yes, the navbar for both the modes is same.  The current navbar is already written with bootstrap so maybe you can work on fixing it, that would be better. Or else if you want to create a new navbar from scratch then please make sure to match the color scheme and aesthetics of the old navbar.
