### ISSUE TITLE
Links are directing back to home page

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/BlogSite#439]
The social media icons used in the home page are redirecting back to the homepage as of now.
I think if appropriate end points are not available currently then these icons should be removed from the home page or if they are available I would like to add them.
Would like to work on it under GSSOC' 21.
I am quite unsure about this issue , so please tell me beforehand if it is unnecessary.
Thanks!

**Comment by Ayush0730** [comment]
I guess they would be adding links later. So we should not remove social icons

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this?

**Comment by RushanKhan1** [comment]
Hey @satcasm, 
@Ayush0730 is right, currently, the icons in the footer are for aesthetic purposes only.  We might add them later.
