### ISSUE TITLE
Remove displaying the short content from home UI

### ISSUE THREAD

**Issue by A7abhilash** [ALPHAVIO/BlogSite#447]
### Feature request-
![2021-03-25 (3)](https://user-images.githubusercontent.com/66360717/112427076-03cb5980-8d5f-11eb-87ab-25bd5e803a5d.png)

As you can see, such a UI isn't an attractive one for the users.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
I thought to not to display the short content on home, dashboard, category, user profiles UI. Just the title, published date, author and read more button would be neater.

### Describe alternatives you've considered
I was thinking to create a separate partials that displays the posts. Because, we can clearly see the the blogs are displayed in same way in 4 different routes(mentioned above).There maybe different blogs with different route but the way to display them is same right... I shall try to work on this also in this pr.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

gssoc21

**Comment by Ayush0730** [comment]
Hey, can I work on this issue? I think we should display short content, 3-4 lines and if the user wants to read complete blog, then he/she can click 'Read more'

**Comment by A7abhilash** [comment]
> Hey, can I work on this issue? I think we should display short content, 3-4 lines and if the user wants to read complete blog, then he/she can click 'Read more'

Im already ready with the pr, just waiting for my old pr #444  to get merged...
