### ISSUE TITLE
Post Content not visible

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/BlogSite#453]
### Feature request-
Post content is not visible while viewing the post on /posts/:id route

### Is your feature request related to a problem? Please describe. (optional)
If the post is large then the content which is present below is not visible as background and text colour is same (not on the top part, but on bottom part). So this problem occurs when the post is large. In small post content is visible

### Describe the solution you'd like
We can change the color of the text or we can put the content inside a container of different background colour.

### Describe how this feature will be useful to our readers.
This will help users see content clearly

### Additional context
Content on top (which is visible) :
![image](https://user-images.githubusercontent.com/68139755/112448277-43eb0600-8d78-11eb-9b1e-831091a761f5.png)
Content at middle (partially visible):
![image](https://user-images.githubusercontent.com/68139755/112448384-59603000-8d78-11eb-95ac-fb4bdc4c417c.png)
Content at end (not visible):
![image](https://user-images.githubusercontent.com/68139755/112448458-6bda6980-8d78-11eb-8075-d195c610c61c.png)
After Selecting :
![image](https://user-images.githubusercontent.com/68139755/112448535-801e6680-8d78-11eb-8442-79977d4387b7.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
What should I do :
#1 : change the color of the text
#2 : put the content inside a container of different background colour.
#3 : Change the background

**Comment by RushanKhan1** [comment]
@Ayush0730 Since our background is of different colors it would be difficult to achieve an easy-to-read contrast with both dark and light colors so I would recommend you put the content inside a container.

**Comment by A7abhilash** [comment]
I have already raised the issue (#446 ) and done with it, just waiting for old pr #444  to get merged, then ill be doing the pr for the issue #447 and then ill do the pr for this issue.

**Comment by Ayush0730** [comment]
Should I close this issue as @A7abhilash is already done with this...
