### ISSUE TITLE
Seems that one of the recent merge has some syntax error in header.ejs

### ISSUE THREAD

**Issue by aanchalrakheja** [ALPHAVIO/BlogSite#468]
![image](https://user-images.githubusercontent.com/68388581/112600695-8a536a00-8e37-11eb-961a-fc069d122263.png)

**Comment by Pranav016** [comment]
I think I got the issue, if you already have the setup on your local system, can you check it ?

just make the categories array in `routes/index.router.js` to an object
```
categories = {[ .... ]}
```
try this and let me know if it works..

**Comment by aanchalrakheja** [comment]
ok will try and revert back

**Comment by aanchalrakheja** [comment]
no it isn't working. Shouldn't the object contain a key value.

**Comment by Pranav016** [comment]
Try these changes and let me know, these would be easier
![image](https://user-images.githubusercontent.com/54665036/112603606-3cd8fc00-8e3b-11eb-8107-c75ad24ce06b.png)

**Comment by aanchalrakheja** [comment]
still giving the same error

**Comment by Pranav016** [comment]
> still giving the same error

I think the one I sent above should work fine because `categories` will be the key and `categories` array is then added as a value for that key.
I might not be able to test and solve it on my system till evening. @AnanyaNegi @RushanKhan1 if you guys have the project setup, can solve the issue..

**Comment by RushanKhan1** [comment]
> > still giving the same error
> 
> I think the one I sent above should work fine because `categories` will be the key and `categories` array is then added as a value for that key.
> I might not be able to test and solve it on my system till evening. @AnanyaNegi @RushanKhan1 if you guys have the project setup, can solve the issue..

I tested branch ``issue-#468`` and it works just fine on my system.

**Comment by Pranav016** [comment]
> > > still giving the same error
> > 
> > 
> > I think the one I sent above should work fine because `categories` will be the key and `categories` array is then added as a value for that key.
> > I might not be able to test and solve it on my system till evening. @AnanyaNegi @RushanKhan1 if you guys have the project setup, can solve the issue..
> 
> I tested branch `issue-#468` and it works just fine on my system.

Thank for testing it 👍 , @aanchalrakheja should I close this issue ?
I think this error is exclusive to your system.
But just to be sure I'll still check it later whenever I get time.
