### ISSUE TITLE
Misaligned page number component

### ISSUE THREAD

**Issue by Arshanshagarwal** [ALPHAVIO/BlogSite#483]
### **Describe the bug**

The Page number bar at the end of the main page is misaligned. It is not centered and aligned a bit towards the left.

### **Expected behavior**

The Page number option can be aesthetically improved and can be aligned properly to the center of the window

### **Screenshots**

![Capture](https://user-images.githubusercontent.com/50940817/112725739-b823d600-8f3f-11eb-8e69-bfb04165630e.PNG)

I am a gssoc'21 participant and would like to work on this particular issue.

**Comment by Ayush0730** [comment]
Can I get assigned for this, if @Arshanshagarwal is not working on this issue?

**Comment by Ayush0730** [comment]
Can I work on this? @RushanKhan1 @Pranav016

I think this issue will not take more than 2 days to fix
