### ISSUE TITLE
Image issue while posting blog

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#485]
### **Describe the bug**
* Blog doesn't get posted unless I attach an image. If I don't attach image then it gives `internal server error`.
![image](https://user-images.githubusercontent.com/54665036/112735689-ed4a1b80-8f73-11eb-85ab-a717ec9fb856.png)
![image](https://user-images.githubusercontent.com/54665036/112735784-005ceb80-8f74-11eb-898e-99754cefa0b3.png)

* When I do attach an image it doesn't show in the blog.
![image](https://user-images.githubusercontent.com/54665036/112735837-5762c080-8f74-11eb-8eea-f5bd5436652c.png)
![image](https://user-images.githubusercontent.com/54665036/112735857-72cdcb80-8f74-11eb-979e-095548ce6ae9.png)

### **To Reproduce**
1. Login
2. Publish blog without attaching any image
3. See error
4. Then try to publish one with image
5. See error

### **Expected behavior**
* Post should be published even if image is not attached.
* If image is attached, it should show up in the blog

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
Yes, I checked this and found that image is not saved in the database. That's why it's not showing

**Comment by priyanshu20** [comment]
> Yes, I checked this and found that image is not saved in the database. That's why it's not showing

Even after saving in the database it is not showing, the ejs template does not have a section for the image.

**Comment by Ayush0730** [comment]
> > Yes, I checked this and found that image is not saved in the database. That's why it's not showing
> 
> Even after saving in the database it is not showing, the ejs template does not have a section for the image.

Yes, you have to create a section for it too
