### ISSUE TITLE
Navbar toggle not working || Mobile view

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#492]
### **Describe the bug**
Navbar toggle not working || Mobile view

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
I am self assigning this issue under gssoc.
/assign

**Comment by tanishq-arya** [comment]
@Pranav016 Hey. I checked everything on my end I think there is an issue with the bootstrap js file. If we change the version back to 4.3.1 then the navbar works fine. If you have any other suggestions please let me know.

**Comment by Pranav016** [comment]
> @Pranav016 Hey. I checked everything on my end I think there is an issue with the bootstrap js file. If we change the version back to 4.3.1 then the navbar works fine. If you have any other suggestions please let me know.
> 
> And if I change the version back we get console error because the file is blocked. Do you want me to make the navbar again ?

Can suggest a fix with the latest bootstrap versions ? We need a long term solution
