### ISSUE TITLE
Add button for compose route from the homepage.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#5]
# About issue-
Add a button for compose route whose get request is mentioned in the `app.js` file, that'll redirect the user to the page where they will write or publish an article.

**Comment by hariramjp777** [comment]
I'd like to work on this issue

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue as mentee of Jwoc.

**Comment by Niveditha18** [comment]
I want to contribute to this issue.

**Comment by sahilsaha7773** [comment]
I would like to work on this
