### ISSUE TITLE
User Profile picture

### ISSUE THREAD

**Issue by Abhinaba006** [ALPHAVIO/BlogSite#512]
### Feature request-
Adding a user profile picture will be great, it will be an option to user, if they like to have profilepicture they can set and in the home page they can go to their profile by clicking on the profile picture.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by RushanKhan1** [comment]
Hey @Abhinaba006, are you still working on this?

**Comment by Abhinaba006** [comment]
@RushanKhan1  It is almost done, I will send it by tomorrow

**Comment by Abhinaba006** [comment]
@RushanKhan1 , I am sorry, I am unable to solve this issue, my approach didn't work properly, please unassign me this task

**Comment by Pranav016** [comment]
> @RushanKhan1 , I am sorry, I am unable to solve this issue, my approach didn't work properly, please unassign me this task

you can unassign it yourself, there should be an unassign button visible in top right

**Comment by Pranav016** [comment]
@Ayush0730 complete the other two issues then get this one assigned. 
Un-assigning this one because one issue you have is `Urgent` and the other one also you've started working on so un-assigning this one for now. Try to have at most 2 assigned at a time

**Comment by Ayush0730** [comment]
> @Ayush0730 complete the other two issues then get this one assigned.
> Un-assigning this one because one issue you have is `Urgent` and the other one also you've started working on so un-assigning this one for now. Try to have at most 2 assigned at a time

Okay, Sorry. From now, I will not take more than two issues at a time.

And I have made a PR for one of my issues, so you can now assign me this, Half work is done on this issue

**Comment by Pranav016** [comment]
> /assign

Yes just comment this again
