### ISSUE TITLE
Inconsistency in routes

### ISSUE THREAD

**Issue by priyanshu20** [ALPHAVIO/BlogSite#532]
There is a lot of variety in how the routes are defined.
Some routes use async some do not
Some routes use arrow functions some do not.

I think we should follow a consistent pattern,
for eg. all routes should have arrow syntax and async keyword.

**Comment by priyanshu20** [comment]
@Pranav016 should this be done?

**Comment by Pranav016** [comment]
> @Pranav016 should this be done?

Yes, go ahead
