### ISSUE TITLE
Bed hover effect in the Buttons of Navbar

### ISSUE THREAD

**Issue by RuchiGitHu** [ALPHAVIO/BlogSite#537]
### **Describe the bug**
When we hover the buttons in navbar (Log in and Sign up) it got disappear due bed color combination.

### **To Reproduce**
1. Go to 'Home page'
2. Click on 'Hover on Log in and Sign in '

### **Expected behavior**
When hover on these buttons it should more visible to user.

### **Screenshots**

![image](https://user-images.githubusercontent.com/71754179/113157493-8f7e3380-9200-11eb-8b76-aa145b4f25d0.png)
![image](https://user-images.githubusercontent.com/71754179/113157548-9c9b2280-9200-11eb-8f22-d6f3d84ac795.png)

### **Additional context**
In the whole website, each and every hovering button is reflecting correctly but no one has same hovering color like Login and Sign in button. It will look good if the hover effect would be same as other hovering buttons.
I want to work on this issue under GSSoC'21.

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
Issue looks genuine 👍 
Can this be resolved asap ?

**Comment by RuchiGitHu** [comment]
> Issue looks genuine 👍
> Can this be resolved asap ?

Yes.

**Comment by RuchiGitHu** [comment]
> Issue looks genuine 👍
> Can this be resolved asap ?

Please review my PR @Pranav016.
Thanks for reply...
