### ISSUE TITLE
Dark mode applies filter on images

### ISSUE THREAD

**Issue by priyanshu20** [ALPHAVIO/BlogSite#546]
### **Describe the bug**
The darkmode library also has an effect on images, which adds a filter ruining the image

### **To Reproduce**
1. Open any blog with an image
2. Toggle on dark mode
3. See error

### **Expected behavior**
Either no filter or a 50% grayscale ,

### **Screenshots**

![Screenshot (142)](https://user-images.githubusercontent.com/59313375/113265067-52de3500-92f1-11eb-8b52-e783ac234853.png)

![Screenshot (143)](https://user-images.githubusercontent.com/59313375/113265107-5d003380-92f1-11eb-888b-cdb9b53d49f1.png)

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
> @Pranav016 have a look.
> Also This is probably an issue with the library being used and we might have to either scrape the dark mode or replace it with a different approach.

You are right, I don't think of scraping it for now. Maybe a different approach for the same can be considered..
