### ISSUE TITLE
Remove inline css from ejs files

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#553]
### **Describe the bug**
Remove all the inline css used in all the ejs files and add that to the styles.css file in public dir under labelled sections (divide code into sections by adding comments).

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
/level3/

**Comment by Ayush0730** [comment]
@Pranav016  Most of the styles are like margin and padding and font-weight and colors. So what should I name the sections?

**Comment by Pranav016** [comment]
> @Pranav016 Most of the styles are like margin and padding and font-weight and colors. So what should I name the sections?

Navigation bar, post section, search, header, footer etc
