### ISSUE TITLE
Spacing after icons

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/BlogSite#556]
There should be spacing after the icons in ```Quick Links``` and ```Address``` ,as of now it seems a bit clustered.
Also I think that underline below the address is not needed.
Would like to work on it if seemed necessary under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/113402405-918ff000-93c2-11eb-9264-d161d0d1334a.png)

**Comment by Pranav016** [comment]
Hyper links usually have underline on hover. I know color change could also work but I feel underline seems to meet the standard
