### ISSUE TITLE
Routing error while accessing /author/:id

### ISSUE THREAD

**Issue by tend2infinity** [ALPHAVIO/BlogSite#562]
### **Describe the bug**
When we access "/author/:id" without actually logging into the website we get redirected to "/error" page, which is kind of misleading because it seems as if the route has some backend error while the problem is just that we are not logged-in.

### **To Reproduce**
1. Go to '/' route
2. Click on the name of any user from the posted blogs to get to '/author/:id'

### **Expected behavior**
We should get redirected to '/log-in' when we are not logged in. We can make the changes in the user.routes.js for this.

### **Video**

https://user-images.githubusercontent.com/61948033/113424092-30c9dd00-93ed-11eb-940a-cd0a8cb2472e.mp4

### **Additional context**

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by aniketlodh** [comment]
@tend2infinity are you working on this issue?

**Comment by tend2infinity** [comment]
@aniketlodh yes
