### ISSUE TITLE
Spacing between buttons

### ISSUE THREAD

**Issue by aniketlodh** [ALPHAVIO/BlogSite#564]
### **Describe the bug**
The sign-up and login buttons don't have any spacing between them. I would like to solve the issue. I'm a GSSOC participant.

### **To Reproduce**
1. Start the app.
2. The buttons appear with no spacing in the navbar

### **Expected behavior**
There should be appropriate spacing between the two buttons.

### **Screenshots**
![Screenshot from 2021-04-03 10-47-48](https://user-images.githubusercontent.com/55927827/113469293-171aab00-946a-11eb-8568-a783abfa1837.png)

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
repeated #500
