### ISSUE TITLE
Adding placeholder property in contact us form

### ISSUE THREAD

**Issue by fatma-sia27** [ALPHAVIO/BlogSite#565]
Hey @Pranav016 , I had seen your website , I think if we add placeholder property in contact us form then it would look awesome . So I request you to please take a look at my issue and please assign it to me so that I can add the above mentioned property.

Thank you

**Comment by fatma-sia27** [comment]
Hey @Pranav016 , I haven't find the main code of contact form in which I can add placeholder property. Please take a look.
Thank you

**Comment by Pranav016** [comment]
Views/contact.ejs

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by fatma-sia27** [comment]
Sorry @Pranav016  .ejs file is not opening in my system. You can assign this issue to someone else.
Thank you

**Comment by SachindraFernando** [comment]
I would like to work on this under gssoc21
