### ISSUE TITLE
Distance between login and sign button is very little

### ISSUE THREAD

**Issue by Atif-reyaz-khan** [ALPHAVIO/BlogSite#588]
### **Describe the bug**
Distance between login and sign button is very little

### **To Reproduce**
1. By creating separation between the tags
![github1](https://user-images.githubusercontent.com/48691336/113515508-90152200-9592-11eb-834c-72cb695ee4ad.jpg)
![github1](https://user-images.githubusercontent.com/48691336/113515520-a327f200-9592-11eb-9acf-0d6a5c57ab40.jpg)

### **Expected behavior**
Their will be sufficient space between the sign in and log in button.

### **Screenshots**

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Pranav016** [comment]
@RushanKhan1 this issue is repeated, kindly close this

**Comment by Atif-reyaz-khan** [comment]
assign me this issue
