### ISSUE TITLE
The navbar is still not responsive in the tablet mode.

### ISSUE THREAD

**Issue by kotwani2883** [ALPHAVIO/BlogSite#595]
### Feature request-
Responsiveness of the Navbar

### Is your feature request related to a problem? Please describe. (optional)
Making the navbar responsive

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by kotwani2883** [comment]
Kindly assign this issue to me as a part of GSSOC-21
Thanks!

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by Atif-reyaz-khan** [comment]
can I work on this issue?I can do it in 1-3hrs

**Comment by satcasm** [comment]
@Pranav016 should I wait as it is already assigned ?

**Comment by satcasm** [comment]
Hey @Pranav016  this issue is still unresolved can I work on this?
