### ISSUE TITLE
Connect with Mongo DB.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#6]
# About issue- 
Connect the website with Mongo database to store the blog posts and make relevant changes to the documentation and app.js file.

Clause- The one who works on connecting the Website to MongoDB also has to work on deployment with Heroku issue #9 
Set up on Heroku and Mongo ATLAS can be done using Alphavio's email that will be shared on Discord dm.

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue as a mentee of JWOC once the coding period starts.
