### ISSUE TITLE
Divide the assets for slugfile

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#606]
### Feature request-
Divide the assets folder into 2, one with all the assets that are used in the website and the other with assets that are not used in the website but are added to the README file like the gif or the banner in README. Also there could be a couple extra logos added there that are not currently used in the website.

When making separate folders in assets, the relative paths for all the images used in the website also need to be updated..

This is being done so that we can send less data for deployment by adding the folder to `.slugignore` and get faster builds for the website.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
@naqeeb2710 can this be done by today ?

**Comment by naqeeb2710** [comment]
> @naqeeb2710 can this be done by today ?

I will try to do this today else it will be done tommorow

**Comment by naqeeb2710** [comment]
what should I name  the second asset folder

**Comment by Pranav016** [comment]
One of them can be assets/main and other can be assets/sub
