### ISSUE TITLE
Proper distance between contact us and sign in 

### ISSUE THREAD

**Issue by Atif-reyaz-khan** [ALPHAVIO/BlogSite#616]
### **Describe the bug**
Their is no proper distance between contact and sign in 

### **To Reproduce**
By creating sufficient distance between contact us and sign in 

### **Expected behavior**
The UI will look much better.

### **Screenshots**
![github2](https://user-images.githubusercontent.com/48691336/113724565-1a36c500-9710-11eb-86e6-aa3839d803d0.png)

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Atif-reyaz-khan** [comment]
assign this to me ?

**Comment by Pranav016** [comment]
repeated issue, already fixed
