### ISSUE TITLE
Alignment of hamburger icon

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/BlogSite#618]
The alignment of hamburger icon in the navbar is not proper.
Would like to fix it and shift it on the right hand side under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/113752666-d9987500-972a-11eb-81ae-0555c23f1224.png)

**Comment by Pranav016** [comment]
repeated #595 
comment here to reopen issue
