### ISSUE TITLE
Number of likes

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/BlogSite#626]
### **Describe the bug**
It is a very minor bug
If there is 1 like then on the post page 1 like should be shown, but currently 1 likes is shown. But for comments 1 comment is shown correctly

### **To Reproduce**
1. Go to 'any post having one like'
2. Click on 'Read More'
3. See error '1 likes'

### **Expected behavior**
1 like should be shown

### **Screenshots**
![image](https://user-images.githubusercontent.com/68139755/113860191-5d05a500-97c3-11eb-912f-7823396724a2.png)

### **Additional context**

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
@Pranav016 Should I also make changes such that if number of comments/likes are 0 , then it should show No comments/likes ??

**Comment by Pranav016** [comment]
I think 0 is fine
