### ISSUE TITLE
Navbar button colors not matching

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#638]
### **Describe the bug**
Navbar button colors not matching with the button colors on rest of the website.
![image](https://user-images.githubusercontent.com/54665036/114026567-02884980-9894-11eb-9b5b-e08d5fac44eb.png)

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by SachindraFernando** [comment]
I would like to work on this issue under GSSoC'21

**Comment by tanishq-arya** [comment]
@Pranav016 I just checked the btn-info class is giving the current color but I can't change it because it is a bootstrap class. I was thinking to create a new class and adding style to that. Should I proceed with this ?

**Comment by Pranav016** [comment]
> @Pranav016 I just checked the btn-info class is giving the current color but I can't change it because it is a bootstrap class. I was thinking to create a new class and adding style to that. Should I proceed with this ?

remove the `btn-info` class and add the class we have given to the other buttons..
