### ISSUE TITLE
Issue in login.

### ISSUE THREAD

**Issue by aniketlodh** [ALPHAVIO/BlogSite#644]
### **Describe the bug**
During login, there is a bug that is generating an error during performing the login functionality. Please assign me this issue. I'm a gssoc participant.
### **To Reproduce**
1. Try to login
2. Enter the credentials then select login

### **Expected behavior**
The expected behaviour would be to successfully log the user in.

### **Screenshots**
![Screenshot from 2021-04-08 19-30-18](https://user-images.githubusercontent.com/55927827/114040089-e9d26080-98a0-11eb-88cb-b9fa3e9bf1d6.png)

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
There is a really big issue in login that I noticed just now after I updated the deploy branch. Can you fix it ? refer to #631 and update your `.env` file (check README)

I wanted to appreciate you since I saw you very actively contribute to this project 👍

**Comment by Pranav016** [comment]
Already signed up users are not able to login since their email is not verified and they cannot sign-up again since the email is already taken. One thing I can do is clear the user db.

**Comment by Pranav016** [comment]
Cleared the db so its fine now I guess..

**Comment by aniketlodh** [comment]
No no, this issue is a bit different. This is resulting because in the code there are typos in the render function.

**Comment by Pranav016** [comment]
>> No no, this issue is a bit different. This is resulting because in the code there are typos in the render function.

>I know your issue is different but I think it coincides
