### ISSUE TITLE
Issue with Email verification

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#651]
### **Describe the bug**
Not able to receive email verification code and redirected to unauthorized page on trying to sign up or login.  

![image](https://user-images.githubusercontent.com/54665036/114063073-d8478380-98b5-11eb-8be8-6693ca5b3e64.png)

Steps to reproduce-
1. Go to the website and try to login

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
I have not done this before but I can try following this https://safwan-du16.medium.com/email-verification-with-node-js-and-nodemailer-3a6363b31060

**Comment by Pranav016** [comment]
It's already been implemented and just needs to be checked once on local system. It's most probably an issue with how the user gets saved and redirected. But yes you can take reference from the article..

**Comment by osamamagdy** [comment]
I think the problem with this is that the server didn't enable the auto emailing first. 
If you're using Gmail I think you should follow this https://www.google.com/settings/security/lesssecureapps

**Comment by Pranav016** [comment]
> I think the problem with this is that the server didn't enable the auto emailing first.
> If you're using Gmail I think you should follow this https://www.google.com/settings/security/lesssecureapps

Oh ok, enabled it now 👍
Will test the feature again

**Comment by tend2infinity** [comment]
@Pranav016 @osamamagdy I guess we need to implement OAUTH2 authentication to cope up with this because it's not working locally even after I configured less secure apps from the google account.

**Comment by osamamagdy** [comment]
@tend2infinity did you recieved the verification email or not ?

**Comment by Pranav016** [comment]
> > I think the problem with this is that the server didn't enable the auto emailing first.
> > If you're using Gmail I think you should follow this https://www.google.com/settings/security/lesssecureapps
> 
> Oh ok, enabled it now 👍
> Will test the feature again

I tested the site again, I checked the sent logged of the email I am using to send the verification email but it was empty..
I think the email is not getting sent..
@osamamagdy I can give you the credentials for Alphavio's email, you can make it work then..
Ping me on discord

**Comment by osamamagdy** [comment]
> > I think the problem with this is that the server didn't enable the auto emailing first.
> > If you're using Gmail I think you should follow this https://www.google.com/settings/security/lesssecureapps
> 
> Oh ok, enabled it now 👍
> Will test the feature again

Just noticed now that we should make this clear in the documentation :
In the Email format that we use, it will redirect users to https://alphavio-daily-journal.herokuapp.com/confirm/:confirmationcode
and this won't work because you will be running on localhost: port so you should replace the sent link with localhost

**Comment by osamamagdy** [comment]
@Pranav016 I think the second option is good to change the link itself
Also I sent you a message at discord please reply

**Comment by Ayush0730** [comment]
Well, I have tested this, allowed less secure apps and then tried to signup, I got the mail with the link to verify account but when I click on that link, I see a message User not found

**Comment by Pranav016** [comment]
Tested it on localhost, works absolutely fine but on deployed app the same code is not working..
We might have to remove this feature or come up with a solution really quick.

**Comment by Pranav016** [comment]
> Well, I have tested this, allowed less secure apps and then tried to signup, I got the mail with the link to verify account but when I click on that link, I see a message User not found

### change this to localhost 
![image](https://user-images.githubusercontent.com/54665036/114129774-dfee4300-991c-11eb-91c9-155d33599b79.png)

**Comment by Pranav016** [comment]
@osamamagdy can you make a PR removing the code, I cannot revert the commit because a number of PRs were merged after this..

**Comment by Ayush0730** [comment]
> @osamamagdy can you make a PR removing the code, I cannot revert the commit because a number of PRs were merged after this..
> 
> anyone who is online can make PR to remove code that was added in #631 , you might get a few extra points for resolving this issue..

Wait, I am doing something like this 

![image](https://user-images.githubusercontent.com/68139755/114130609-943c9900-991e-11eb-9195-d5683e255de3.png)
This will take the hostname automatically from the url

**Comment by Pranav016** [comment]
> > @osamamagdy can you make a PR removing the code, I cannot revert the commit because a number of PRs were merged after this..
> > anyone who is online can make PR to remove code that was added in #631 , you might get a few extra points for resolving this issue..
> 
> Wait, I am doing something like this
> 
> ![image](https://user-images.githubusercontent.com/68139755/114130609-943c9900-991e-11eb-9195-d5683e255de3.png)
> This will take the hostname automatically from the url

Oh ok, still giving error?
Then we have to remove the feature..

**Comment by Ayush0730** [comment]
> > > @osamamagdy can you make a PR removing the code, I cannot revert the commit because a number of PRs were merged after this..
> > > anyone who is online can make PR to remove code that was added in #631 , you might get a few extra points for resolving this issue..
> > 
> > 
> > Wait, I am doing something like this
> > ![image](https://user-images.githubusercontent.com/68139755/114130609-943c9900-991e-11eb-9195-d5683e255de3.png)
> > This will take the hostname automatically from the url
> 
> Oh ok, still giving error?
> Then we have to remove the feature..

request.headers.protocol is undefined

**Comment by Ayush0730** [comment]
will http be okay? As on localhost https request will not work

**Comment by Pranav016** [comment]
> > > > @osamamagdy can you make a PR removing the code, I cannot revert the commit because a number of PRs were merged after this..
> > > > anyone who is online can make PR to remove code that was added in #631 , you might get a few extra points for resolving this issue..
> > > 
> > > 
> > > Wait, I am doing something like this
> > > ![image](https://user-images.githubusercontent.com/68139755/114130609-943c9900-991e-11eb-9195-d5683e255de3.png)
> > > This will take the hostname automatically from the url
> > 
> > 
> > Oh ok, still giving error?
> > Then we have to remove the feature..
> 
> request.headers.protocol is undefined

Can you make a PR removing additions in #631

**Comment by Ayush0730** [comment]
> > > > > @osamamagdy can you make a PR removing the code, I cannot revert the commit because a number of PRs were merged after this..
> > > > > anyone who is online can make PR to remove code that was added in #631 , you might get a few extra points for resolving this issue..
> > > > 
> > > > 
> > > > Wait, I am doing something like this
> > > > ![image](https://user-images.githubusercontent.com/68139755/114130609-943c9900-991e-11eb-9195-d5683e255de3.png)
> > > > This will take the hostname automatically from the url
> > > 
> > > 
> > > Oh ok, still giving error?
> > > Then we have to remove the feature..
> > 
> > 
> > request.headers.protocol is undefined
> 
> Can you make a PR removing additions in #631

Can you please check once, I am creating a PR with some changes, works fine on localhost, check on live website, if you can

**Comment by Pranav016** [comment]
> > > > > > @osamamagdy can you make a PR removing the code, I cannot revert the commit because a number of PRs were merged after this..
> > > > > > anyone who is online can make PR to remove code that was added in #631 , you might get a few extra points for resolving this issue..
> > > > > 
> > > > > 
> > > > > Wait, I am doing something like this
> > > > > ![image](https://user-images.githubusercontent.com/68139755/114130609-943c9900-991e-11eb-9195-d5683e255de3.png)
> > > > > This will take the hostname automatically from the url
> > > > 
> > > > 
> > > > Oh ok, still giving error?
> > > > Then we have to remove the feature..
> > > 
> > > 
> > > request.headers.protocol is undefined
> > 
> > 
> > Can you make a PR removing additions in #631
> 
> Can you please check once, I am creating a PR with some changes, works fine on localhost, check on live website, if you can

Already checked on live website, what changes are you proposing?

**Comment by Ayush0730** [comment]
> > > > > > > @osamamagdy can you make a PR removing the code, I cannot revert the commit because a number of PRs were merged after this..
> > > > > > > anyone who is online can make PR to remove code that was added in #631 , you might get a few extra points for resolving this issue..
> > > > > > 
> > > > > > 
> > > > > > Wait, I am doing something like this
> > > > > > ![image](https://user-images.githubusercontent.com/68139755/114130609-943c9900-991e-11eb-9195-d5683e255de3.png)
> > > > > > This will take the hostname automatically from the url
> > > > > 
> > > > > 
> > > > > Oh ok, still giving error?
> > > > > Then we have to remove the feature..
> > > > 
> > > > 
> > > > request.headers.protocol is undefined
> > > 
> > > 
> > > Can you make a PR removing additions in #631
> > 
> > 
> > Can you please check once, I am creating a PR with some changes, works fine on localhost, check on live website, if you can
> 
> Already checked on live website, what changes are you proposing?
> 
> Yes you can make PR, I'll check

Raised a PR, please check
