### ISSUE TITLE
Separate the js files in public dir and update paths

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#655]
### Feature request-
Put all the `.js` files present in the public dir to the public/js folder and update their paths where ever they are used. (most probably as script tags in the footer.)

Also there are a couple of scripts in the footer that are not required for all the pages thus they slow down the loading process unnecessarily. Put them at the end of the files that they are used instead of adding in the footer that is used in all the pages.

Example `/js/showHidePassword.js` and `/checkPasswordMatch.js` are not used in all the pages so they don't need to be in the footer. Add them at the end of the files that they are used in and **manage the opening and closing tags in the footer and that file when script tag is added at the bottom** 

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
public dir to public folder? I didn't get it. Could you please elaborate

**Comment by Pranav016** [comment]
> public dir to public folder? I didn't get it. Could you please elaborate

my bad, updated the description

**Comment by Ayush0730** [comment]
> > public dir to public folder? I didn't get it. Could you please elaborate
> 
> my bad, updated the description

Okay, got it! Thanks
