### ISSUE TITLE
Reduce margin between category input box and button

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#670]
### **Describe the bug**
Reduce margin between category input and button. Doesn't look symmetrical with all the other buttons.
![image](https://user-images.githubusercontent.com/54665036/114274523-63eb1c80-9a3c-11eb-91b7-fb68f8cf4ab3.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ritika539** [comment]
Hey @Pranav016 !

I want to work on this issue under GSSoC '21.

**Comment by tanishq-arya** [comment]
Do you want it to be like this ? @Pranav016 
![image](https://user-images.githubusercontent.com/77333275/114276244-6735d680-9a43-11eb-90a1-1693ede83f50.png)

**Comment by Pranav016** [comment]
> Do you want it to be like this ? @Pranav016
> ![image](https://user-images.githubusercontent.com/77333275/114276244-6735d680-9a43-11eb-90a1-1693ede83f50.png)

Yes
