### ISSUE TITLE
Changing Font Color 

### ISSUE THREAD

**Issue by Ritika539** [ALPHAVIO/BlogSite#671]
### **Describe the bug**
The background color and the font color is quite similar due to which the site doesn't look good. 

### **Expected behavior**
Just want to change the  font color.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
can elaborate what changes are you suggesting and what will you be doing..

I think font color other than that in the navbar is fine because it helps us contrast the dark mode

**Comment by Ritika539** [comment]
ok! I was talking about the font which is in blue colour.
yeah, in the dark mode it's looking cool but not in the normal mode.

**Comment by Pranav016** [comment]
> ok! I was talking about the font which is in blue colour.
> yeah, in the dark mode it's looking cool but not in the normal mode.

Everything is a shade of blue, which blue are you talking about ? 
Can explain your idea with a screenshot maybe?

**Comment by Pranav016** [comment]
closing for now, re-raise issue if necessary..
