### ISSUE TITLE
Navbar color 

### ISSUE THREAD

**Issue by Harshit-Pathak** [ALPHAVIO/BlogSite#685]
### **Describe the bug**
The navbar color makes reading links in light mode difficult 
 
### **Expected behavior**
changing the current color with a darker color so that the links become more readable to user

please assign me this issue as a participant in gssoc'21

**Comment by Pranav016** [comment]
color of the links is already being changed in another issue..

**Comment by Harshit-Pathak** [comment]
sir my issue was to change the navbar's color and not the links color, please assign me with this issue
