### ISSUE TITLE
Adding Functionality to Email in Address

### ISSUE THREAD

**Issue by tarunsinghofficial** [ALPHAVIO/BlogSite#689]
### **Describe the bug**
The Email doesn't open any mail app when clicked. We can add a code to add functionality to the Email so, that users can directly contact without copying the email and then do copy-paste thing.

### **Screenshots**
![image](https://user-images.githubusercontent.com/62840625/114572734-62686100-9c95-11eb-9973-7a5f3006c54e.png)

### **Additional context**
I am working under GSSoC'21 so, please add me under this.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
just adding `mailto` to the link would do the job, but I think we already have an emailing feature in contact us page so is this really necessary ?

**Comment by tarunsinghofficial** [comment]
> just adding `mailto` to the link would do the job, but I think we already have an emailing feature in contact us page so is this really necessary ?

I think it will help the users but if you do not need to add it, that's okay.

**Comment by Pranav016** [comment]
ok
