### ISSUE TITLE
Assitance chatbot

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#69]
### **Is your feature request related to a problem? Please describe the feature**
Add an assistance chatbot to the website.

### **Describe how this feature will be useful to our readers.**
It will help the new users on how to use the website/ how to publish vlog and clear doubts if any. It would also help them to tell us about any issue they face regarding the website.

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue @Pranav016 ! Assign it to me.
