### ISSUE TITLE
Style the scroll to top button

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#692]
### Feature request-
Style the scroll to top button

![image](https://user-images.githubusercontent.com/54665036/114647674-22d46000-9cfb-11eb-9dbf-1d6e675c9ae8.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
I have styled the scroll to top similar to the other buttons on the page. Also I tried to change the icon to arrow in a circle and others but it didn't look that good. If you have anything else in mind for please let me know. 

![Screenshot (1228)](https://user-images.githubusercontent.com/77333275/114978745-505e0c80-9ea7-11eb-8611-84be5ef30f8c.png)
![Screenshot (1229)](https://user-images.githubusercontent.com/77333275/114978748-518f3980-9ea7-11eb-8ee6-4c5f144f4928.png)
![Screenshot (1227)](https://user-images.githubusercontent.com/77333275/114978740-4e944900-9ea7-11eb-8ffc-13893aa71561.png)

**Comment by Pranav016** [comment]
> @Pranav016 @AnanyaNegi I have styled the scroll to top similar to the other buttons on the page. Also I tried to change the icon to arrow in a circle and others but it didn't look that good. If you have anything else in mind for please let me know.
> 
> ![Screenshot (1228)](https://user-images.githubusercontent.com/77333275/114978745-505e0c80-9ea7-11eb-8611-84be5ef30f8c.png)
> ![Screenshot (1229)](https://user-images.githubusercontent.com/77333275/114978748-518f3980-9ea7-11eb-8ee6-4c5f144f4928.png)
> ![Screenshot (1227)](https://user-images.githubusercontent.com/77333275/114978740-4e944900-9ea7-11eb-8ffc-13893aa71561.png)

I think it looks fine in the third pic, simple and elegant. I hope you reused pre-made colors and classes in css instead of making new ones unless absolutely necessary (keep the css code clean) otherwise looks good 👍

**Comment by tanishq-arya** [comment]
I'll make a PR then. Yes I reused the CSS.  The first image is when you hover over the button.
