### ISSUE TITLE
Improve the header and the footer.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#7]
# About issue-
- Improve the design of the header and the footer.
- Remove the current footer and replace it with a nicely designed footer with some hypothetical info and social media icons.
- Make sure the components are responsive.

**Comment by pankajkumarbij** [comment]
I would like to work on this issue as a participant of JWOC.

**Comment by Niveditha18** [comment]
@Pranav016, I want to contribute for this issue

**Comment by sahilsaha7773** [comment]
I would like to work on this

**Comment by shreetama123** [comment]
@Pranav016 I want to contribute in this project

**Comment by mcmonojit** [comment]
@Pranav016 , I would like to work on this issue. Can I be assigned ?
