### ISSUE TITLE
Inconsistency in styling of comment and like button

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#711]
### Feature request-
Make the comment button orange like the `Like` button and turn to blue on hover.

![image](https://user-images.githubusercontent.com/54665036/115294368-2857fd00-a176-11eb-8e81-e271d2702bf9.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
Currently, like button is set such that on hover white border changes to blue color
![image](https://user-images.githubusercontent.com/68139755/115353984-c54a8280-a1d6-11eb-8dd6-e452eb1e54ff.png)

But other buttons don't have same hover effects, on hover over other buttons color changes but border remains white
![image](https://user-images.githubusercontent.com/68139755/115354277-15c1e000-a1d7-11eb-907f-f6959d7a4091.png)

So should I make like button same as others too? or make other buttons similar to like button

**Comment by Pranav016** [comment]
> Currently, like button is set such that on hover white border changes to blue color
> ![image](https://user-images.githubusercontent.com/68139755/115353984-c54a8280-a1d6-11eb-8dd6-e452eb1e54ff.png)
> 
> But other buttons don't have same hover effects, on hover over other buttons color changes but border remains white
> ![image](https://user-images.githubusercontent.com/68139755/115354277-15c1e000-a1d7-11eb-907f-f6959d7a4091.png)
> 
> So should I make like button same as others too? or make other buttons similar to like button

Yes make the Like button same shade of blue (on hover) as the other buttons
