### ISSUE TITLE
Improve button styling

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#716]
### **Describe the bug**
Update the button styles to match the theme of the rest of the website. (reuse the existing classes)
![image](https://user-images.githubusercontent.com/54665036/115317325-e8eed800-a198-11eb-97e1-b17b01573fc9.png)  

Make the buttons look like this
![image](https://user-images.githubusercontent.com/54665036/115317599-8518df00-a199-11eb-856d-1ca9e67ba532.png)

### **To Reproduce**
1. Login
1. Click on Dashboard
1. Click on edit info
1. See the bug

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
Can you please tell me how to login without creating a user ?

**Comment by Pranav016** [comment]
> Can you please tell me how to login without creating a user ?

You can't :)

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/115664127-11283380-a35f-11eb-8cc4-64907e18c66f.png)

**Comment by tanishq-arya** [comment]
Should I go ahead and style the Cancel one too ?

**Comment by tanishq-arya** [comment]
![Screenshot (1340)](https://user-images.githubusercontent.com/77333275/115667146-1f784e80-a363-11eb-8ccd-0a106bc14bf0.png)
![Screenshot (1339)](https://user-images.githubusercontent.com/77333275/115667153-21421200-a363-11eb-9104-224b6684ebea.png)

**Comment by tanishq-arya** [comment]
Red one is on hover. I think red looks better so we should not add any hover and make it stay red only. What do you think?

**Comment by Pranav016** [comment]
> Red one is on hover. I think red looks better so we should not add any hover and make it stay red only. What do you think?

Yes, looks good
