### ISSUE TITLE
Color of font in about page

### ISSUE THREAD

**Issue by RuchiGitHu** [ALPHAVIO/BlogSite#726]
### Feature request-
Color of font in about page is similar with the color in background. The half content of statement in left is not visible as the right side of the statement because of dark shade and light shade of  background color in left and right
 
Left Side of statement is not visible as it should be:
![image](https://user-images.githubusercontent.com/71754179/115596524-d1e5de00-a29d-11eb-85e8-2affc2ef0372.png)
But because of light color in background same font color is more visible then left :
![image](https://user-images.githubusercontent.com/71754179/115596651-f346ca00-a29d-11eb-848e-67108cc8ecc0.png)

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
I would like to change font color of statement so that for same background the content could be more visible and readable.

### Describe how this feature will be useful to our readers.
The website should have good user experience and if important content is not showing effectively then how they will like to read it. 

Example : You can't see black font in black background color.

### Additional context
![image](https://user-images.githubusercontent.com/71754179/115597315-bfb86f80-a29e-11eb-9a2b-2e9f4b474c26.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
repeated issue #717
