### ISSUE TITLE
Bug in server starting

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/BlogSite#737]
### **Describe the bug**
On starting the server on localhost, server is not starting as mailgun API is not provided but it is required in index router, previously it was required on the /contact route

### **To Reproduce**
1. Update your local branch
2. Start server'
3. See error

### **Expected behavior**
The mailgun API should be required on /contact route

### **Screenshots**
![image](https://user-images.githubusercontent.com/68139755/115828699-b3155200-a42b-11eb-8ea8-3aae0f400a56.png)

### **Additional context**
I was working on my previous issue and then I updated my local branch and found this bug

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
@Pranav016 please review this

**Comment by Pranav016** [comment]
yes, you are right!
Should I fix it or should tell you how to ?

**Comment by Pranav016** [comment]
wait I'll tell you

**Comment by Ayush0730** [comment]
> wait I'll tell you

I just need to move require statement to contact route??

**Comment by Pranav016** [comment]
> > wait I'll tell you
> 
> I just need to move require statement to contact route??

No that would give linting error.
Try this 
```
if (process.env.NODE_ENV !== 'production') {
  const sendMail= *just paste the whole line here*
}
```

Confirm to me if this works

**Comment by Pranav016** [comment]
@Ayush0730 check the correction and let me know `if (process.env.NODE_ENV === 'production') {`

**Comment by Ayush0730** [comment]
> @Ayush0730 check the correction and let me know `if (process.env.NODE_ENV === 'production') {`

Okay

**Comment by Ayush0730** [comment]
It's working now

**Comment by Pranav016** [comment]
> It's working now

Ok 👍 you can make a PR for it now

**Comment by Ayush0730** [comment]
But it's again giving linting errors

![image](https://user-images.githubusercontent.com/68139755/115832385-7ac44280-a430-11eb-87fc-d57fe265a515.png)

**Comment by Pranav016** [comment]
just add the require in `/contact` router and add a comment over it `// eslint-disable-line`. This should work for now..
I'll solve the issue later when I get time
