### ISSUE TITLE
Improve the overall UI.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#8]
# About issue-
Improve the User experience by using better color combinations and adding interactive components and animations to the website.

**Comment by hariramjp777** [comment]
I'd like to work on this issue. Please assign it to me @Pranav016

**Comment by Pabitra145** [comment]
As apart of jwoc , i want to contribute in it

**Comment by Pabitra145** [comment]
As a part of jwoc , i want to contribute in it

**Comment by Pabitra145** [comment]
ok sir i will submit it as soon as possible

**Comment by Pranav016** [comment]
Are you still working on this  @Pabitra145 ?
