### ISSUE TITLE
Deploy the website using Heroku

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#9]
# About issue-
- Deploy the website on [Heroku](www.heroku.com).

- Before Deploying, make sure that the Data base for the project has been setup and you are able to store the data base keys in a hidden file ( like a `.env` file ) on heroku to connect the website to the DB.

Also READ #6  -> Important

**Comment by Subhra264** [comment]
Want to work on this issue

**Comment by Subhra264** [comment]
Under JWOC

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue as a mentee of Jwoc

**Comment by Pranav016** [comment]
> Want to work on this issue

this issue has to be worked #6 
Will able to do them?

**Comment by Subhra264** [comment]
Yes sure!

> > Want to work on this issue
> 
> this issue has to be worked #6
> Will you be able to do them?

Yes sure!

**Comment by karunkarthik-git** [comment]
@Pranav016 how can you unassign me when I worked halfway and I've even mentioned here that I want to work with this issue. This isnt fair.
