### ISSUE TITLE
Improve the buttons on the home page.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#90]
### Enhancement request:
The style of the buttons should be improved and it should be consistent since all the buttons are of different style. Buttons with animations on hover would help improve the overall experience.

### Describe how this enhancement will be useful to our readers.
Improves user experience of using the website.

**Comment by sahilsaha7773** [comment]
I want to work on this issue as a part of jwoc.

**Comment by Pranav016** [comment]
Let me know if you still want to work on this.

**Comment by Pranav016** [comment]
> I want to work on this issue as a part of jwoc.

Let me know if you still want to work on this, I'll reassign.

**Comment by sahilsaha7773** [comment]
> > I want to work on this issue as a part of jwoc.
> 
> Let me know if you still want to work on this, I'll reassign.

Sorry for the delay, I was busy with my college assignments, I have updated the PR now

**Comment by Pranav016** [comment]
> > > I want to work on this issue as a part of jwoc.
> > 
> > 
> > Let me know if you still want to work on this, I'll reassign.
> 
> Sorry for the delay, I was busy with my college assignments, I have updated the PR now

No problem, I'll review the PR tomorrow morning 👍

**Comment by Pranav016** [comment]
Closed via #96
