### ISSUE TITLE
Adding Preloader to the site

### ISSUE THREAD

**Issue by tusharjain0022** [ALPHAVIO/BlogSite#95]
### Is your feature request related to a problem? Please describe.
The user has to wait for a while the page is loading and might close the site assuming the site is not working.

### Describe the solution you'd like
Adding Preloader to the site will be a good option.
### Describe alternatives you've considered
Optimizing the whole site and minimizing the loading time could also solve this problem but this seems to be not an optimized and smart solution.

### Describe how this feature will be useful to our readers.
 It'll grab the audience till the page is loading.

### Additional context
https://i.stack.imgur.com/aI3V9.gif

**Comment by Pranav016** [comment]
Good idea
